### ISSUE TITLE
dirbscan after stuck

### ISSUE THREAD

**Issue by 0x240x23elu** [j3ssie/Osmedeus#102]
[ESTIMATED] DirbScan module executed in 550.34 seconds.
----------------------------------------------------------------------
[*] Sending done notification to slack
[*] Sending report notification to slack

after send dirbscan its stuck . no process after that

**Comment by j3ssie** [comment]
Yeah because there is nothing else to run on main routine. The reason why it's still up is for you to access the Web UI.
It's will stop when you run the API server in another process. [Detail](https://j3ssie.github.io/Osmedeus/architecture/)
