### ISSUE TITLE
Replace DirbScan with Dirsearch

### ISSUE THREAD

**Issue by attacker34** [j3ssie/Osmedeus#104]
Dear @j3ssie 

Please replace Dirbscan which is giving a lot of errors with dirsearch

```
https://github.com/maurosoria/dirsearch

```

 it will be a better replacement i believe.

Sincerely,

**Comment by j3ssie** [comment]
Yeah, I used to use it for **DirbScan** module but it seems consuming too many resources for running a list of URLs. Furthermore, options `-o` in `-U` options doesn't output anything.

Let me know if you see any good reason to using it for a list of urls.

**Comment by attacker34** [comment]
@j3ssie ffuf has been updated in original repos. but don't know whether your tool is extracting the updated version or not.

**Comment by j3ssie** [comment]
I've just update dirscan with some new awesome features from **ffuf** :)
