### ISSUE TITLE
--noslack option doesn't close the tool

### ISSUE THREAD

**Issue by ATO7** [j3ssie/Osmedeus#105]
--noslack option doesn't close the tool when it's finish
![Screenshot from 2019-10-27 16-44-42](https://user-images.githubusercontent.com/33043331/67636450-40c8bd80-f8d9-11e9-8664-2add793d7be6.png)

I'm using xterm and need the console to exit but it can't because the tool don't close itself after finishing.
I use in this way:
./osmedeus.py -m subdomain -t domain.com --noslack

**Comment by j3ssie** [comment]
Yeah, it's still running to allow you to access web UI on it. That's status just mean it's gonna send noti to slack in case you configured slack token and doesn't do anything if you're not. Maybe I should strip that status later
 
 https://github.com/j3ssie/Osmedeus/issues/102
