### ISSUE TITLE
Stuck  on SubdomainScanning 

### ISSUE THREAD

**Issue by alinixd** [j3ssie/Osmedeus#107]
Hey, 
Seems to be really useful tool so thank you.
My only issue is it stuck on SubdomainScanning module. 
It there a way to fix it?
![Capture](https://user-images.githubusercontent.com/45742475/68087237-7da62e80-fe5c-11e9-8e87-a6eaa14e0561.PNG)

**Comment by j3ssie** [comment]
Look like you still using a legacy version which is not supported anymore.
Please consider to upgrade to v2 and do it again.

**Comment by alinixd** [comment]
python2?
