### ISSUE TITLE
problem in waiting to module

### ISSUE THREAD

**Issue by shelu16** [j3ssie/osmedeus#108]
hi I have problem .I was start scan then it is stuck whole night waiting for subdomain module . and now it's every time it's stuck there

**Comment by j3ssie** [comment]
Can you delete a workspaces folder in `~/.osmedeus/workspaces/` and run it again? Or try a new target to see any different?

**Comment by zeeebbbrrraaa** [comment]
Where file workspaces

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
