### ISSUE TITLE
Got error on vps

### ISSUE THREAD

**Issue by dzul89** [j3ssie/Osmedeus#11]
Hi.

I got the below error when i tried to run

> Traceback (most recent call last):
>   File "./osmedeus.py", line 8, in <module>
>     from core import routine
>   File "/root/Osmedeus/core/routine.py", line 10, in <module>
>     from modules import portscan
>   File "/root/Osmedeus/modules/portscan.py", line 11, in <module>
>     from libnmap.parser import NmapParser
> ImportError: No module named 'libnmap'

**Comment by j3ssie** [comment]
This error because you didn't install `python-libnmap` on your machine.
And what is your OS?

**Comment by wilgert** [comment]
I get the same error on Kali. Even after doing `pip install python-libnmap`.

**Comment by alikat500** [comment]
The same error on Kali. I also installed python-libnmap  and received the same error.
I tried to run osmedeus.py using Python3 and received the same error:
root@kali:~/Osmedeus# python3 osmedeus.py
Traceback (most recent call last):
  File "osmedeus.py", line 8, in <module>
    from core import routine
  File "/root/Osmedeus/core/routine.py", line 10, in <module>
    from modules import portscan
  File "/root/Osmedeus/modules/portscan.py", line 11, in <module>
    from libnmap.parser import NmapParser
ModuleNotFoundError: No module named 'libnmap'

==================================================

root@kali:~/Osmedeus# lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2019.1
Codename:	n/a
root@kali:~/Osmedeus# uname -a
Linux kali 4.19.0-kali3-amd64 #1 SMP Debian 4.19.20-1kali1 (2019-02-14) x86_64 GNU/Linux
root@kali:~/Osmedeus#

**Comment by j3ssie** [comment]
That's the library used while I do testing but I forget to remove.
It's should be fixed now, really sorry about that.

**Comment by alikat500** [comment]
Thanks for fixing the error. However, when I ran the script I received the same error. I cloned and reinstalled. This time I received the following message. This i s a Kali 209.1:

            Osmedeus v1.1 by @j3ssiejjj

                    ¯\_(ツ)_/¯
        
[*] Config file detected: core/config.conf
--~~~=:>[ Starting Flask API ]>
Traceback (most recent call last):
  File "core/app.py", line 13, in <module>
    from flask import abort
ModuleNotFoundError: No module named 'flask'
[-] Fail to set config, Please check Flask API !!!
root@kali:~/Osmedeus#

**Comment by dzul89** [comment]
thank for fixing the error. after i install the libmap it done. but have a another problem. i will inform later

**Comment by smartis63** [comment]
root@PC192:/home/smartis/Scrivania/Osmedeus# ./osmedeus.py -t spotify.com
Traceback (most recent call last):
  File "./osmedeus.py", line 10, in <module>
    from lib.client import config
  File "/home/smartis/Scrivania/Osmedeus/lib/client/config.py", line 7, in <module>
    from lib.core import execute
  File "/home/smartis/Scrivania/Osmedeus/lib/core/execute.py", line 8, in <module>
    from core import utils
ImportError: cannot import name 'utils' from 'core' (/usr/local/lib/python3.8/dist-packages/ufonet-1.6-py3.8.egg/core/__init__.py)
