### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by M0dred** [j3ssie/Osmedeus#111]
I have a mistake when I changed the  ~/.osmedeus/client.conf username and password
Now I can't start ./osmedeus.py

[-] Authentication failed
[-] Can't login to get JWT
[05/Dec/2019 12:01:27] "POST /auth/api/token/ HTTP/1.1" 401 63

**Comment by j3ssie** [comment]
Osmedeus use Django authentication system to mange users [detail](https://j3ssie.github.io/Osmedeus/installation/user-management/). That's file just a place to store credentials so you don't have to type it every time.

If you don't know how to change it just delete `~/.osmedeus/` folder and run `install.sh` again.

**Comment by M0dred** [comment]
Thank u dude
