### ISSUE TITLE
subfinder: no go files

### ISSUE THREAD

**Issue by mablanco** [j3ssie/Osmedeus#112]
Hi j3ssie. When building docker image for version 2.2, I receive this message:
```
[+] Installing subfinder 
package github.com/subfinder/subfinder: no Go files in /root/go/src/github.com/subfinder/subfinder
```

Is it a problem or nothing to take care of? Best regards

PS: Just uploaded the image to Docker hub

**Comment by j3ssie** [comment]
Yeah that's happened because **subfinder** just update their repo. I'll update it soon.

**Comment by j3ssie** [comment]
Look good now. Open an issue again if you have any problem

**Comment by mablanco** [comment]
Just uploaded new Docker image. It works now!
