### ISSUE TITLE
still waiting for StoScan module ....... (2 hours)

### ISSUE THREAD

**Issue by M0dred** [j3ssie/osmedeus#114]
After Starting pre routine for DirbScan .......
always show

[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module
[*] Waiting for StoScan module

**Comment by j3ssie** [comment]
It really shows `pre routine for DirbScan` but waiting for StoScan?

**Comment by jembsd** [comment]
Was one of the domains you fed in not live? I think massdns hangs if the source file exists but is empty. $WORKSPACE/probing/raw-all-$OUTPUT.txt. Check console to see what it's waiting for?

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
