### ISSUE TITLE
Metabigor installation failed

### ISSUE THREAD

**Issue by Smismi11** [j3ssie/Osmedeus#116]
Metabigor has been rewritten in go on the same github repo https://github.com/j3ssie/Metabigor
For this reason the pip installation in install.sh fails.

**Comment by Smismi11** [comment]
I guess the the call "$PLUGINS_PATH/Metabigor/metabigor.py -m ip -t $TARGET -o $WORKSPACE/ipspace/range-$OUTPUT.txt" won't work either

**Comment by j3ssie** [comment]
This should be fixed now.
Forget to update this one because I focusing on the new upgrade of Osmedeus.

**Comment by attacker34** [comment]
Hi @j3ssie 

i am getting this Error after testing a clean installation today:

```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'Metabigor/requirements.txt'

```
