### ISSUE TITLE
Workpsace not found on Report mode

### ISSUE THREAD

**Issue by Ezio51** [j3ssie/osmedeus#117]
![Captura de pantalla de 2020-01-04 15-23-52](https://user-images.githubusercontent.com/13500012/71769986-3bee3e80-2f06-11ea-84e7-23152eeec384.png)

**And just stop there, in every single type of scan mode avaiable**

**Comment by j3ssie** [comment]
What command did you run?
Can you confirm the workspace folder exist in `~/.osmedeus/workspaces/<your_workspace_here>`/

**Comment by gilmarwsr** [comment]
I have this same issue. My workspace folder exists.

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
