### ISSUE TITLE
Add Open Redirection Tool & Support Progress Bar for each Module

### ISSUE THREAD

**Issue by attacker34** [j3ssie/osmedeus#118]
Hi  @j3ssie 

Please add this Tool for Open Redirection Checking:

```
https://github.com/ak1t4/open-redirect-scanner/

```

Add Progress bar as many people here are complaining about being stuck with any module..It will be good thing to add Progress bar for each module along with estimated time remaining for each module to be executed.

**Comment by j3ssie** [comment]
Hi @attacker34,
Looks like a great tool but I think it's also can be done via a signature in my Scanner Framework https://github.com/jaeles-project/jaeles
I will test it out before I add it.

**Comment by attacker34** [comment]
hmm. @j3ssie  I think it is simple tool and should be integrated within Osmedeus. I have discovered some more payloads here,  you can remove duplicates payloads:

```
https://github.com/cujanovic/Open-Redirect-Payloads/blob/master/Open-Redirect-payloads.txt
https://github.com/payloadbox/open-redirect-payload-list
https://pentester.land/cheatsheets/2018/11/02/open-redirect-cheatsheet.html

```

Sincerely,

**Comment by attacker34** [comment]
Hi @j3ssie  here is another Tool CRLF injector which should be added

```
https://github.com/MichaelStott/CRLF-Injection-Scanner

```

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
