### ISSUE TITLE
Documentation on GUI workspace

### ISSUE THREAD

**Issue by LennonCMJ** [j3ssie/Osmedeus#12]
Hi I saw that there the GUI workspace mode screenshot but the documentation and commands have no mention of it.
Would like to run it independently to check on the status of scans. Would be helpful

**Comment by j3ssie** [comment]
Basically, workspaces on the Web UI is listing the workspaces folder and show what done for specific workspace.
So you can totally run it independently by running flask server using this command `python3 core/app.py run` and run `osmedeus.py -t example.com --client` for other target.

**Comment by LennonCMJ** [comment]
Thanks for the reply this is really helpful. :)
