### ISSUE TITLE
How i delete old scans of the list

### ISSUE THREAD

**Issue by thisEdgarMarquez** [j3ssie/Osmedeus#120]
Hello @j3ssie , i would like to know how to remove my scans from the list reports,summaries and logs. 

Thank for this great tool

**Comment by j3ssie** [comment]
Just delete a workspace folder in `~/.osmedeus/workspaces/workspace_need_to_detele`.
Note that the record of that workspace still exist but don't worry it will auto update the new result when you run it again.

**Comment by thisEdgarMarquez** [comment]
Ok, Is there any way to delete the registry?

**Comment by j3ssie** [comment]
Currently, you have to delete it manually in `Osmedeus/server/db.sqlite3` via sqlite command.
