### ISSUE TITLE
functionality to load an Amass configuration file

### ISSUE THREAD

**Issue by thisEdgarMarquez** [j3ssie/Osmedeus#123]
Hi @j3ssie , I have modified the project code to add the functionality of loading a configuration file for Amass.

You can see the commit on my fork https://github.com/thisEdgarMarquez/Osmedeus/commit/71707ef8a9bd7b1d4fc25c47644a41fa73344103 #

**Comment by j3ssie** [comment]
The main purpose of Osmedeus is you don't need to provide any API key but I'm really glad that you can custom your own.

I know we can even use that config without api key so maybe that'll help customize it more easier. I'll update the main flow soon.

Thanks for your contribution.

**Comment by thisEdgarMarquez** [comment]
Ok I understand it for those who are interested.
