### ISSUE TITLE
Waiting for LinkFinding module

### ISSUE THREAD

**Issue by 0ks3iio** [j3ssie/Osmedeus#124]
![image](https://user-images.githubusercontent.com/8078301/73944584-ce329980-492d-11ea-8d20-301630d08709.png)

![image](https://user-images.githubusercontent.com/8078301/73944663-e86c7780-492d-11ea-9d87-7528c16f44fe.png)

Stuck after running

**Comment by j3ssie** [comment]
Can you just delete `Osmedeus/server/db.sqlite3` and run the following commands below to create new db.
```
python3 server/manage.py makemigrations
python3 server/manage.py migrate
python3 server/manage.py makemigrations api
python3 server/manage.py migrate api
python3 scripts/init.py
python3 scripts/reload.py
```

Otherwise you can remove the linkfinding module from this file `https://github.com/j3ssie/Osmedeus/blob/master/lib/mode/general.py#L40`

**Comment by 0ks3iio** [comment]
Thanks
