### ISSUE TITLE
pip

### ISSUE THREAD

**Issue by kaal-kali** [j3ssie/Osmedeus#125]
https://github.com/Yukinoshita47/Yuki-Chan-The-Auto-Pentest.git

**Comment by kaal-kali** [comment]
/install.sh: line 259: pip3: command not found                            
Traceback (most recent call last):                                         
  File "setup.py", line 2, in <module>                                     
    from setuptools import setup, find_packages                            
ModuleNotFoundError: No module named 'setuptools'

**Comment by j3ssie** [comment]
You need to install **pip3** your machine first.
