### ISSUE TITLE
Fix Issues: ImportError: cannot import name 'utils'

### ISSUE THREAD

**Issue by shino-337** [j3ssie/osmedeus#135]
Please change line 8 from lib/core/execute.py
from core import utils -> from lib.core import utils

**Comment by j3ssie** [comment]
Why you need that?

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
