### ISSUE TITLE
Error in Start command

### ISSUE THREAD

**Issue by meetgyn** [j3ssie/Osmedeus#136]
Traceback (most recent call last):
  File "./osmedeus.py", line 9, in <module>
    from lib.core import utils
  File "/opt/ferramentas/tools/Osmedeus/lib/core/utils.py", line 67
    print(f'{G} + {GR}' + str(text))
                      ^
SyntaxError: invalid syntax

**Comment by j3ssie** [comment]
Make sure you have at least **python3.6+**.

**Comment by meetgyn** [comment]
I am trying to again the installation, in Debian 9.0, with Python3.7 and the error continues the same.
