### ISSUE TITLE
Error while running FFUF Module

### ISSUE THREAD

**Issue by kentbayron** [j3ssie/osmedeus#138]
[](url)
![error](https://user-images.githubusercontent.com/16931096/76960600-c1568c00-6956-11ea-9e16-48b2260135da.png)
Error while running ffuf will lead to DirbScan freeze. 
![error2](https://user-images.githubusercontent.com/16931096/76960739-07abeb00-6957-11ea-8cb6-d34cbcf9440a.png)

Host: Ubuntu 18.04 LTS (DigitalOcean Droplet)

**Comment by j3ssie** [comment]
Can you run that command directly to verify it can run well?

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
