### ISSUE TITLE
Running on VPS

### ISSUE THREAD

**Issue by Handerllon** [j3ssie/osmedeus#141]
I´m having some issues running the service on VPS.

From other issues I have seen, the server can be ran in a persistent mode with

`python3 Osmedeus/core/app.py -b 0.0.0.0 -p 5000`

The problem I'm facing is that the `/core` folder does not exist anymore on the current main branch.

Is it there another way to run the server? I checked the docs but no info was found.

**Comment by hiddengearz** [comment]
I'm also struggling to figure this out

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
