### ISSUE TITLE
Integrate paramspider 

### ISSUE THREAD

**Issue by abuvanth** [j3ssie/osmedeus#146]
https://github.com/devanshbatham/ParamSpider

**Comment by fabaff** [comment]
Not only for `Osmedeus` but also other tools and installation process would it be useful if paramspider would provide a `setup.py` file and is available from PyPI.

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
