### ISSUE TITLE
Waiting for ScreenShot module for more than 10h

### ISSUE THREAD

**Issue by dokkillo** [j3ssie/Osmedeus#148]
[*] Waiting for ScreenShot module
[*] Waiting for ScreenShot module
[*] Waiting for ScreenShot module
[*] Waiting for ScreenShot module
[*] Waiting for ScreenShot module
[*] Waiting for ScreenShot module
[*] Waiting for ScreenShot module
[*] Waiting for ScreenShot module
[*] Waiting for ScreenShot module
[*] Waiting for ScreenShot module
[*] Waiting for ScreenShot module
[*] Waiting for ScreenShot module
[*] Waiting for ScreenShot module
[*] Waiting for ScreenShot module
[*] Waiting for ScreenShot module
[*] Waiting for ScreenShot module
[*] Waiting for ScreenShot module
[*] Waiting for ScreenShot module
[*] Waiting for ScreenShot module

I tested this in Ubuntu 19:

- in my computer
- in vps
- root user
- normal user
- diferents domains

All time i have this issue.... any idea that what can i do? or any idea for test more?

Regards

**Comment by manerod** [comment]
> [_] Waiting for ScreenShot module [_] Waiting for ScreenShot module
> [_] Waiting for ScreenShot module [_] Waiting for ScreenShot module
> [_] Waiting for ScreenShot module [_] Waiting for ScreenShot module
> [_] Waiting for ScreenShot module [_] Waiting for ScreenShot module
> [_] Waiting for ScreenShot module [_] Waiting for ScreenShot module
> [_] Waiting for ScreenShot module [_] Waiting for ScreenShot module
> [_] Waiting for ScreenShot module [_] Waiting for ScreenShot module
> [_] Waiting for ScreenShot module [_] Waiting for ScreenShot module
> [_] Waiting for ScreenShot module [_] Waiting for ScreenShot module
> [*] Waiting for ScreenShot module
> 
> I tested this in Ubuntu 19:
> 
> * in my computer
> * in vps
> * root user
> * normal user
> * diferents domains
> 
> All time i have this issue.... any idea that what can i do? or any idea for test more?
> 
> Regards

Same problem here

**Comment by dokkillo** [comment]
Hello,

Now it works, I just updated my pip3 version to lastest version :)
