### ISSUE TITLE
Process get stuck at "DirbScan"

### ISSUE THREAD

**Issue by DarkReitor** [j3ssie/osmedeus#149]
The scan get stuck in here, tried in docker and normal launch, any solution?

**Comment by dokkillo** [comment]
Hi,
Its not stuck, just the api program it just waiting... just open another terminal and write 
sudo python3 osmedeus.py -i ANOTHER-URL  --client

It will run again

**Comment by 1UC1F3R616** [comment]
@dokkillo It is talking time to scan with complete wordlist. You mean this right?

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
