### ISSUE TITLE
subdomains duplicates

### ISSUE THREAD

**Issue by mhmh55516** [j3ssie/osmedeus#152]
filtering duplicates subdomains not work
![Capture](https://user-images.githubusercontent.com/28407784/81359345-346bbb80-90d9-11ea-82a6-8e23583b1731.PNG)

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
