### ISSUE TITLE
Getting Error with amass @  /lib/workflow/direct.py

### ISSUE THREAD

**Issue by attacker007** [j3ssie/osmedeus#153]
Hi @j3ssie 

While tool runs this command from /lib/workflow/direct.py or general.py

```

"cmd": "$GO_PATH/amass enum -timeout 10 -active -max-dns-queries 10000 -include-unresolvable -dir $WORKSPACE/subdomain/amass-$OUTPUT -d $TARGET -o $WORKSPACE/subdomain/$OUTPUT-amass.txt",
--

```

I am getting this Error:

```
Flag Provided but not defined:-include-unresolvable

```

First of all I looked and yes this flag is there in Amass usage directory. But I think you somehow changed the Command structure thats why it's giving error.

For time being, I've tried to remove this flag from "direct.py" , "general.py" but still getting Same Error ...I think there is another file which need modifications.

Sincerely,

**Comment by attacker007** [comment]
Hi @j3ssie  still getting this Error on Ubuntu... Can you please check? 


Thanks !

**Comment by kireyn** [comment]
Also get this error on Ubuntu 18.04

**Comment by kernelzeroday** [comment]
In order to fix this, modify the references in lib/workflow/ for both general and direct, save the file, then run scripts/reload.py

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
