### ISSUE TITLE
How do you start the webserver in persistant mode?

### ISSUE THREAD

**Issue by hiddengearz** [j3ssie/osmedeus#156]
Hello,

I've setup the docker-compose.yml file and found that whenever I start the container the ./osmedeus.py script runs once and the container shutsdown. If i set the container to always restart it just runs ./osmedeus.py over and over and over, without keeping the webserver up. Is it possible to launch the webserver and have it running constantly?

**Comment by fabaff** [comment]
You can start the server manually with:

```bash
$ python3 server/manage.py runserver
```

For Docker I assume that you would have to adjust the settings in the `Dockerfile` and re-build it. Also, would require that you run the the container in interactive mode to be able to start a scan.

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
