### ISSUE TITLE
Report/Logs/Sammary without option to choose

### ISSUE THREAD

**Issue by alinixd** [j3ssie/osmedeus#157]
Hey,
First of all this is a great tool.
Secondary, suddenly I can't choose anything at localhost:8000.
![Captu124re](https://user-images.githubusercontent.com/45742475/82756798-0975ad00-9de5-11ea-9ff5-a9404dc40f3e.PNG)

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
