### ISSUE TITLE
Remove the dependency on arjun

### ISSUE THREAD

**Issue by fabaff** [j3ssie/osmedeus#158]
I'm in process of packaging `Osmedeus` for the Fedora Package Collection. A lot of parts are already there, but to make it happen at least the dependency on `arjun` has to go. Preferably be replaced with another  maintained tool/library which provide the needed features.

For full disclosure, I submitted the needed chances to allow me to create a package of `arjun` in 
https://github.com/s0md3v/Arjun/pull/22 a while ago but nothing happen.

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
