### ISSUE TITLE
-m vuln error "Nmap VulnScan"

### ISSUE THREAD

**Issue by jordantsap** [j3ssie/Osmedeus#16]
--~~~=:>[ Vulnerable Scanning ]>
[+] Starting Nmap VulnScan
Traceback (most recent call last):
  File "./osmedeus.py", line 158, in <module>
    main()
  File "./osmedeus.py", line 154, in main
    parsing_argument(args)
  File "./osmedeus.py", line 74, in parsing_argument
    single_target(options)
  File "./osmedeus.py", line 88, in single_target
    routine.specific(options, module)
  File "/media/jordan/2.1/Pentest/Osmedeus/core/routine.py", line 89, in specific
    vulnscan.VulnScan(options)
  File "/media/jordan/2.1/Pentest/Osmedeus/modules/vulnscan.py", line 17, in __init__
    self.initial()
  File "/media/jordan/2.1/Pentest/Osmedeus/modules/vulnscan.py", line 26, in initial
    self.nmap_vuln()
  File "/media/jordan/2.1/Pentest/Osmedeus/modules/vulnscan.py", line 32, in nmap_vuln
    main_json['Modules'][self.module_name] = []
TypeError: 'NoneType' object is not subscriptable
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt

**Comment by j3ssie** [comment]
Some module is currently cannot run directly for now. I'm working on new features to resolve that.
So basically your error is the vuln module required a list of subdomains from subdomain scanning module just running `-m subdomain` first.

**Comment by jordantsap** [comment]
Why dont you let the issue open so that people know that there is a bug?

**Comment by j3ssie** [comment]
Working in progress for resume routine and fix bug on some direct module.

**Comment by j3ssie** [comment]
It's should be fixed now check out the wiki page for more options.
TL;DR: `./osmedeus -t result_folder -m vuln -i very_long_host.txt`

**Comment by loublink** [comment]
Having the same issue, I tried to use the direct option and received the following error:
[+] Direct mode detect
[-] You you want to specific -i options

I used the exact syntax: ./osmedeus -t result_folder -m vuln -i very_long_host.txt

**Comment by jordantsap** [comment]
My error made me uninstall it and dont use it again so i propose you to open a new issue about yours

**Comment by j3ssie** [comment]
I just tested and It works like a charm. So make sure you read this [wiki](https://github.com/j3ssie/Osmedeus/wiki/Advanced-Usage).

In  this command `./osmedeus -t result_folder -m vuln -i very_long_host.txt`. `-i very_long_host.txt` which mean very_long_host.txt is a file contain a bunch of hosts and `-t result_folder` which is name of the folder contain the result.

This error `[-] You want to specific -i options` which mean maybe your file doesn't exist or you not specific a -i option.

Let me know if any error.
