### ISSUE TITLE
the slow option has no effect in majority modules

### ISSUE THREAD

**Issue by junmoxiao** [j3ssie/osmedeus#164]
such as in portscan.
Even I use --slow 'all', the masscan still use same arguments to scan .
I think use "nmap -sT" instead of masscan when set "--slow" option is better, sometimes the scan speed is not important.

**Comment by junmoxiao** [comment]
when I use this tool in https://bandwagonhost.com/ . In portscan phase ,the vps will be suspend immediately.

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
