### ISSUE TITLE
Feature: Use the modules for web hosts

### ISSUE THREAD

**Issue by g33kyshivam** [j3ssie/osmedeus#165]
Can we have a feature when we can supply running http/s web hosts and take advantage of other modules like cors/fingerprinting

**Comment by attacker007** [comment]
You need to read the Wiki of this tool.. You will find option over there for feeding http/s hosts with command

```
./osmedeus.py -T list_of_target.txt

```

Please close the ticket.

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
