### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by Mirhatyasar** [j3ssie/Osmedeus#166]
I successfully installed it but when i try to run it gives me a error which says ModuleNotFoundError: No module named 'requests' i tried to install requests again but it says Requirement already satisfied.

![error](https://user-images.githubusercontent.com/40506686/84951053-d65dcb00-b0bd-11ea-9a98-f61ad9d5ae6d.png)

**Comment by attacker007** [comment]
try this "pip install requests" or "pip3 install requests"... also use "sudo" while running command

**Comment by Mirhatyasar** [comment]
Thanks for your comment! I was having issues with pip3 it was giving me SSL errors in Kali Linux i was not able to install any package with pip3 so after some research i made this youtube search: https://www.youtube.com/results?search_query=kali+linux+pip3+install+ssl+error+solution 
and found solution for pip3 ssl error in kali linux
