### ISSUE TITLE
TypeError: just_shutdown_flask() missing 1 required positional argument: 'options'

### ISSUE THREAD

**Issue by robdollard** [j3ssie/Osmedeus#17]
Hi, after checking dirsearch, the next module starts working, but then an error occurs, and this work stops.

![image](https://user-images.githubusercontent.com/40629638/56423887-6d1ad600-62c7-11e9-91f9-40ef2f43f255.png)

**Comment by j3ssie** [comment]
Thank you for your feedback. 
I forget to pass argument when updating the API architecture.
It's should be fixed now.
