### ISSUE TITLE
Monitor Mode

### ISSUE THREAD

**Issue by segliran** [j3ssie/osmedeus#170]
Hi, 
I've noticed that the Monitor mode scan isn't performed any action, please correct me if I'm misunderstood this module.

If I'm wrong - can you share with us more detailed documentation regarding this module?

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
