### ISSUE TITLE
Authentication failed at: http://127.0.0.1:8000/auth/api/token/

### ISSUE THREAD

**Issue by s41n1k** [j3ssie/osmedeus#172]
I am facing this problem, I'm running it on root priv

```
[*] Loading config file from: /root/.osmedeus/client.conf
[*] Look like Django API already ran
[-] Authentication failed at: http://127.0.0.1:8000/auth/api/token/

        [!] This might happened by running Osmedeus with sudo but the install process running with normal user
        You should install the whole Osmedeus and running it with root user.
        Or whitelist masscan + nmap in sudoers file because it's required sudo permission.

[-] Can't login to get JWT
```

**Comment by s41n1k** [comment]
anyone here to solve this problem ?

**Comment by 1UC1F3R616** [comment]
@s41n1k run as sudo

**Comment by Delson704557** [comment]
> @s41n1k run as sudo

Thanks Mahnn

**Comment by bhavsec** [comment]
I am using root account, I installed using root and running using root too, still getting this error. 

```
[*] Loading config file from: /root/.osmedeus/client.conf
[-] Authentication failed at: http://127.0.0.1:8000/auth/api/token/

        [!] This might happened by running Osmedeus with sudo but the install process running with normal user
        You should install the whole Osmedeus and running it with root user.
        Or whitelist masscan + nmap in sudoers file because it's required sudo permission.
        
[-] Can't login to get JWT

```

**Comment by 1UC1F3R616** [comment]
@bhavsec you can use docker if possible.

- can u check manually what response u get when u visit `http://127.0.0.1:8000/auth/api/token/` because ur Django app is up as there is no warning or error about that?
- Does Osmedeus crash after this error or it's still running? If it's still running then try visiting and login in to the app by taking credentials from the file.

- And y don't u install as no-root? try this also

**Comment by bhavsec** [comment]
Thanks, but this command helped me out:

`python3 server/manage.py runserver 0.0.0.0:8000`

I must have checked the [documentation](https://j3ssie.github.io/Osmedeus/) before using it.

**Comment by tomsec** [comment]
I have installed the program and able to access the WebUI as well but I am not able to login to the portal. Every time it says Incorrect Credentials. I tried the default credentials, as well as I, modified it under ~/.osmedeus/client.info but still, it's not working. Apart from that, I tried running the server using sudo but still faced the same issue.

**Comment by 1UC1F3R616** [comment]
> I have installed the program and able to access the WebUI as well but I am not able to login to the portal. Every time it says Incorrect Credentials. I tried the default credentials, as well as I, modified it under ~/.osmedeus/client.info but still, it's not working. Apart from that, I tried running the server using sudo but still faced the same issue.

Because the correct (new changed path) is /root/.osmedeus/client.info

To access this path use 'sudo su' and then you can cd over there or use
'cat /root/.osmedius/client.info'

or create a new super user and then login with those credentials
'py server/manage.py createsuperuser'

Hope this helps you🙌🏻

**Comment by moshealon76** [comment]
> I have installed the program and able to access the WebUI as well but I am not able to login to the portal. Every time it says Incorrect Credentials. I tried the default credentials, as well as I, modified it under ~/.osmedeus/client.info but still, it's not working. Apart from that, I tried running the server using sudo but still faced the same issue.

hey man, have the same issue, maybe did you find any solutios?

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
