### ISSUE TITLE
Fuzzing issue

### ISSUE THREAD

**Issue by dipakpanchal456** [j3ssie/osmedeus#173]
While doing fuzzing It's getting double [dots] coming like "Fille name [dot] and extension e.g. 'admin..php'"
e.g. 2 scenarios here

[Status: 403, Size: 1299, Words: 693 Lines: 31]
*HOST: https://ab.example.com
*FUZZ: admin2/index..jsp

[Status: 301, Size: 185, Words: 6 Lines: 8]
*HOST: https://abc.example.com
*FUZZ: admin2/index..jsp

Fix it as soon as possible because it may be 200 ok but due double dots it's giving 4xx or 3xx.

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
