### ISSUE TITLE
Slack report problem?

### ISSUE THREAD

**Issue by j0ni3r1** [j3ssie/osmedeus#174]
Hello j3ssie first your tool is really really amazing and very useful.

My problem is i get notifications for the status channel  and only a few files in report channel.

The scan over but seems the report never send. already try to generate the report before and after using the command "osemdeus.py -t example.com --report html --slack" and all sum report but still not working.

The steps i follow are the next

> I add this to  ~/.bashrc
> 
> export LOG_CHANNEL=commands
> export STATUS_CHANNEL=status
> export REPORT_CHANNEL=report
> export STDS_CHANNEL=stdout
> export SLACK_BOT_TOKEN=xoxXXXX
> 
> update with source ~/.bashrc and use the reload.py script

S i need to configure something else in the tool or slack?

Is there any way to get the html report? there is a way to get a .zip for the workspace?

Thanks!

**Comment by nagarajcruze** [comment]
hey can you tell me how you made slack notification work?
i added all this but still i'm not getting notifications.. :/

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
