### ISSUE TITLE
Amass Error

### ISSUE THREAD

**Issue by Vibhu025** [j3ssie/osmedeus#176]
On running I get the following error 
```bash
/root/Osmedeus/plugins/go/amass enum -timeout 10 -active -max-dns-queries 10000 -include-unresolvable -dir /root/.osmedeus/workspaces/{Redacted} -d {Redacted} -o /root/.osmedeus/workspaces/{Redacted} 
```

On running the command in a new terminal I get 
```bash
flag provided but not defined: -include-unresolvable
```

**Comment by pdelteil** [comment]
Same here. Installed the latest version.

**Comment by DefenceLogic** [comment]
Running the default docker image with 

```bash
[*] Execute: /home/Osmedeus/plugins/go/amass enum -timeout 10 -active -max-dns-queries 10000 -include-unresolvable -dir /root/.osmedeus/workspaces/example.com/subdomain/amass-example.com -d example.com -o /root/.osmedeus/workspaces/example.com/subdomain/example.com-amass.txt
flag provided but not defined: -include-unresolvable
----------------------------------------------------------------------
Something went wrong with the command below:
/home/Osmedeus/plugins/go/amass enum -timeout 10 -active -max-dns-queries 10000 -include-unresolvable -dir /root/.osmedeus/workspaces/example.com/subdomain/amass-example.com -d example.com -o /root/.osmedeus/workspaces/example.com/subdomain/example.com-amass.txt
```

The default command  pass an unsupported command line argument "include-unresolvable", if you run this manually with out the flag amass works.

Is there a way to pass tell osmedeus to run amass without the -include-unresolvable flag? I would like to be able to use amass with a configuration file similiar to https://github.com/OWASP/Amass/blob/master/examples/config.ini. Something like below

```bash
/home/Osmedeus/plugins/go/amass enum -timeout 10 -active -max-dns-queries 10000 -config <path to config file in docker image> -dir /root/.osmedeus/workspaces/example.com/subdomain/amass-example.com -d example.com -o /root/.osmedeus/workspaces/example.com/subdomain/example.com-amass.txt
```

**Comment by JLP04** [comment]
same here.

**Comment by DefenceLogic** [comment]
Found the solution for this problem. The file that needs to be changed is in the lib/workflow/general.py at line 23. Just remove the "-include-unresolvable" from the command line. 

So just do the following

```bash
git clone https://github.com/j3ssie/Osmedeus
cd Osmedeus/lib/worflow
nano general.py
./install.sh
```

**Comment by jo3rg** [comment]
They have removed the `include-unresolvable` option from amass:
https://github.com/OWASP/Amass/commit/e42b30ed6aa1f332ca040fbe534014d8358d875f
I will push a pull request in a few

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
