### ISSUE TITLE
Getting error while running on VPS

### ISSUE THREAD

**Issue by jayjani007** [j3ssie/osmedeus#177]
I am getting below error while running tool on VPS:

```
[-] Authentication failed at: http://x.x.x.x:5000/auth/api/token/

        [!] This might happened by running Osmedeus with sudo but the install process running with normal user
        You should install the whole Osmedeus and running it with root user.
        Or whitelist masscan + nmap in sudoers file because it's required sudo permission.
        
[-] Can't login to get JWT
```

Could you please help me with this?

**Comment by shariarr** [comment]
any one to solve this issue??Having same error.

**Comment by Liquid1998** [comment]
@jayjani007 check on which port you django server is running....i guess it will be on 8000....so change the port from 5000 to 8000 in /root/.osmedeus/client.conf...it will work

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
