### ISSUE TITLE
Export Workspaces?

### ISSUE THREAD

**Issue by 00xData** [j3ssie/osmedeus#178]
Is posible to export/import workspaces?

I try to move all folder to new workstation, but when i go to the GUI i dont see the folders.

**Comment by Andhox** [comment]
same bro
i run it on termux android

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
