### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by MiracDasmine** [j3ssie/osmedeus#181]
ImportError: cannot import name 'utils' from 'core' (/usr/local/lib/python3.8/dist-packages/xsser-1.8.3-py3.8.egg/core/__init__.py)

**Comment by rockysec** [comment]
I have the same error

Traceback (most recent call last):
  File "osmedeus.py", line 9, in <module>
    from lib.core import utils
ImportError: No module named core

**Comment by GraylockInc** [comment]
Yup, broken here too

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
