### ISSUE TITLE
Installation.sh -> Error {subfinder | gitrob | gitleaks}

### ISSUE THREAD

**Issue by mrsivak93** [j3ssie/osmedeus#184]
Dear j3ssie, 

Receiving following error when I try to install the pre-requirement and dependency via .install.sh. 

```
[+] Installing subfinder
cannot find package "github.com/projectdiscovery/subfinder/cmd/subfinder" in any of:
        /home/user/.go/src/github.com/projectdiscovery/subfinder/cmd/subfinder (from $GOROOT)
        /home/user/go/src/github.com/projectdiscovery/subfinder/cmd/subfinder (from $GOPATH)

[+] Installing gitrob
        # github.com/michenriksen/gitrob/core
../go/src/github.com/michenriksen/gitrob/core/router.go:41:54: too few values in assetfs.AssetFS literal

[+] Installing gitleaks
code in directory /home/user/go/src/github.com/go-git/go-billy/osfs expects import "github.com/go-git/go-billy/v5/osfs"
cannot find package "github.com/google/go-github/v31/github" in any of:
        /home/user/.go/src/github.com/google/go-github/v31/github (from $GOROOT)
     /home/user/go/src/github.com/google/go-github/v31/github (from $GOPATH)

```

Note: I am trying to install it on Kali Linux. 

Thanks

**Comment by shivammusic** [comment]
Hello @mrsivak93 @j3ssie ,
i am having same problem with installation on kali linux, not able to install subfinder as well as gitrob, gitleaks.
in past i had installation issues only with gitrob, gitleaks, massdns.

**Comment by hellresistor** [comment]
Friends, Near line 112 of install.sh

put this `github.com/projectdiscovery/subfinder/v2/cmd/subfinder` instead this ` github.com/projectdiscovery/subfinder`

**Comment by shivammusic** [comment]
@hellresistor Thank you so much.

can you help to solve this gitrob and gitleaks errors during installation.

[+] Installing gitrob
        # github.com/michenriksen/gitrob/core
../go/src/github.com/michenriksen/gitrob/core/router.go:41:54: too few values in assetfs.AssetFS literal

[+] Installing gitleaks
code in directory /home/user/go/src/github.com/go-git/go-billy/osfs expects import "github.com/go-git/go-billy/v5/osfs"
cannot find package "github.com/google/go-github/v31/github" in any of:
        /home/user/.go/src/github.com/google/go-github/v31/github (from $GOROOT)
     /home/user/go/src/github.com/google/go-github/v31/github (from $GOPATH)

**Comment by hellresistor** [comment]
are you logon with root account or execute `sudo ./install` ?

**Comment by mrsivak93** [comment]
> Friends, Near line 112 of install.sh
> 
> put this `github.com/projectdiscovery/subfinder/v2/cmd/subfinder` instead this ` github.com/projectdiscovery/subfinder`
> 
> I think it is a quick update @j3ssie
> sed -i 's/github.com/projectdiscovery/subfinder/github.com/projectdiscovery/subfinder/v2/cmd/subfinder/' install.sh

Thanks for your support bro.

**Comment by mrsivak93** [comment]
> are you logon with root account or execute `sudo ./install` ? What OS ? use Kali

I am also facing the same issues. Even when I executed the command in root privilege.

**Comment by shivammusic** [comment]
@hellresistor I am using kali and i was log on with root account.

**Comment by hellresistor** [comment]
I have getting an error during installation on building lxml package

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
