### ISSUE TITLE
always getting stuked at "DirbScan"

### ISSUE THREAD

**Issue by 4rch-54m43l** [j3ssie/osmedeus#185]
I'm always getting stuck at the dirbscanning. I don't know what's happening but I always exclude the "dirb" module!
Here are the command and result :-
Command = {# osmedeus -x "dirb,screenshot,burp,git" -t <target.com> }
(It scanned every other module and it showed me that it skipped the screenshot module but didn't work for dirb)
Result = {[RUN] Starting DirbScan
----------------------------------------------------------------------
[*] Detect Ignore module: DirbScan }
waited for an hour!
I don't want this module to be executed what should i do? @j3ssie

**Comment by hellresistor** [comment]
Check to
![osmedeusDirbScan](https://user-images.githubusercontent.com/50468493/95250515-1f26c480-0812-11eb-8151-66b178f65080.png)

**Comment by amiralkizaru** [comment]
Hello I have the same issue
I get stuck when I ignore the fuzz module `dirbscan`
![Untitled](https://user-images.githubusercontent.com/32225186/96011362-ae763e00-0df7-11eb-914f-b9a915fd865c.png)
Any work around guys?

Regards

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
