### ISSUE TITLE
gorm.io issues

### ISSUE THREAD

**Issue by shariarr** [j3ssie/Osmedeus#196]
package gorm.io/gorm/clause: unrecognized import path "gorm.io/gorm/clause": reading https://gorm.io/gorm/clause?go-get=1: 404 Not Found
package gorm.io/gorm/logger: unrecognized import path "gorm.io/gorm/logger": reading https://gorm.io/gorm/logger?go-get=1: 404 Not Found
package gorm.io/gorm/schema: unrecognized import path "gorm.io/gorm/schema": reading https://gorm.io/gorm/schema?go-get=1: 404 Not Found
package gorm.io/gorm/callbacks: unrecognized import path "gorm.io/gorm/callbacks": reading https://gorm.io/gorm/callbacks?go-get=1: 404 Not Found
package gorm.io/gorm/migrator: unrecognized import path "gorm.io/gorm/migrator": reading https://gorm.io/gorm/migrator?go-get=1: 404 Not Found

**Comment by 0xjson** [comment]
go get -u gorm.io/gorm
