### ISSUE TITLE
CORStest fails and UI doesnt load on browser

### ISSUE THREAD

**Issue by shahriarr-sec** [j3ssie/osmedeus#198]
[*] Execute: python2 /root/tools/framework/Osmedeus/plugins/CORStest/corstest.py -p 50 /root/.osmedeus/workspaces/example.com/probing/http-example.com.txt | tee /root/.osmedeus/workspaces/example.com/cors/example.com-corstest.txt
Traceback (most recent call last):
  File "/root/tools/framework/Osmedeus/plugins/CORStest/corstest.py", line 7, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

################################################################################################
Also UI does not load in browser.
![Capture](https://user-images.githubusercontent.com/75485377/105067875-6461c000-5aaa-11eb-889a-bff326d53103.PNG)

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
