### ISSUE TITLE
Feature: Add a paramspider with dalfox combo

### ISSUE THREAD

**Issue by xalgord** [j3ssie/osmedeus#199]
It is the best combo i have ever used. Paramspider tool used to extract all parameters of a domain and dalfox is multipurpose automated powerful and fast tool written in go to find XSS, open redirection , api's and other vulnerabilities.

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
