### ISSUE TITLE
No config.conf file in root directory

### ISSUE THREAD

**Issue by jordantsap** [j3ssie/Osmedeus#20]
I try to access the browser gui but i cannot find the credentials.
Clicking at the info with "Where to find credentials" it says that i can find them in config.conf file but there no as such in the root dir.
Should i rename the "template-config.conf" file???

**Comment by j3ssie** [comment]
If you're not custom anything it's should be in `core/config.conf`.
Check out this wiki page for more [detail](https://github.com/j3ssie/Osmedeus/wiki/How-does-it-work)
