### ISSUE TITLE
WebAnalyze -- Cannot unmarshal array into Go struct

### ISSUE THREAD

**Issue by lootfinder** [j3ssie/osmedeus#202]
https://github.com/j3ssie/Osmedeus/blob/b705b6bd7c6059bf68a6a657d55a866e65d91596/install.sh#L102

Would you like me to make a pull request with a temp fix? 

credit to @maxrev17 with link to older technologies.json at https://github.com/rverton/webanalyze/issues/45:  https://raw.githubusercontent.com/AliasIO/wappalyzer/965f0fcad60c8dc774e8b949ca01b12565f2de09/src/technologies.json

I can confirm this fixes the issue.

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
