### ISSUE TITLE
[Feature request] Replace waybackurls with gau

### ISSUE THREAD

**Issue by shelld3v** [j3ssie/osmedeus#208]
[gau](https://github.com/lc/gau) does not just fetch links from Wayback Machine, but also AlienVault's Open Threat Exchange and Common Crawl

**Comment by GraylockInc** [comment]
Gau plus plus might be a better option

**Comment by shelld3v** [comment]
Oh there is? :rofl:

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
