### ISSUE TITLE
go tools are not getting installed 

### ISSUE THREAD

**Issue by 0xabdulhaq** [j3ssie/osmedeus#218]
![image](https://user-images.githubusercontent.com/52556735/145030444-4c37159e-f756-42ed-a1f2-afced75bb121.png)
The new golang installation has been changed to `go install pkg@version` because of which the tools are not getting installed.

More details on go install are here https://go.dev/doc/go-get-install-deprecation

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
