### ISSUE TITLE
+Feature+Option (TOR access and proxy settings)

### ISSUE THREAD

**Issue by lucas-apd** [j3ssie/osmedeus#22]
I recently wrote a similar code. I "stole" osmedeus ideas (Congrats!), so I'll try to collaborate : D

1 - Allowing use of a proxy is essential for anyone who uses whitelists in their security technologies.

2 - Check if it is possible to access the page through the TOR network.

Something like...
"
def get_tor_session():

    session = req.session()

    session.proxies = {'http':  'socks5://127.0.0.1:9050',
                       'https': 'socks5://127.0.0.1:9050'}
    return session

def test_tor(url):

    tor = "unknown"
    ts = get_tor_session()
    uagent = "configs here"

    tr= ts.get(url, headers=uagent, verify=False, timeout=10)

    if tr is not None:
        tor_status = tr.status_code
        tor_content = tr.text
        tor_header = dict(tr.headers)
        tor_conn = tr.headers['connection']

    if tor_status == 200 or tor_conn != "close":
        tor = "Pass (Block please!)"
    elif "captcha" in tor_content:
        tor = "Captcha (How about Block? :p)"
    elif "Access Denied" in tor_content:
        tor = "B l o c k e d !  s2"
    else:
        tor = "Unknown"
   print (tor)
    ts.close()
"
OK! Sorry!  I'm not a developer!  :p

**Comment by j3ssie** [comment]
Yeah using proxy or tor is absolutely possible so it's already on the TODO list for a while but I'm just focused on another feature instead of that.
Anyway, this feature will coming soon :D.

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
