### ISSUE TITLE
Scanning multiple domains in the same workspace overwrites results

### ISSUE THREAD

**Issue by cosmin91ro** [j3ssie/osmedeus#221]
when running the following command 

```
osmedeus scan -T list_of_targets.txt -w workspace_name
```

where list_of_targets.txt has some content like:
```
domain.com
domain.org
domain.net
```

the tool takes each domain at a time and scans it, but the results for domain.org overwrites the results for domain.com and so on,  so that when the scan is complete, you'll only have the results for the last target - domain.net

**Comment by j3ssie** [comment]
I think you run the wrong command. The right one should be `osmedeus scan -T list_of_targets.txt`

**Comment by cosmin91ro** [comment]
what if I need to put all the targets in one single workspace?

**Comment by j3ssie** [comment]
You can use the `osmedeus scan -T list-targets.txt -W /opt/root-workspace`.
Note I just added that option in v4.0.1, so make sure you update the new version.
