### ISSUE TITLE
Packer command not installed

### ISSUE THREAD

**Issue by mablanco** [j3ssie/osmedeus#224]
Hi @j3ssie. When running the `osmedeus utils` command, it complains about not finding the `packer` binary:
```
error checking core programs: /root/osmedeus-base/binaries/packer -h
```
I haven found any mention about Packer in the installation script. Is Packer a prerequisite before installing/using Osmedeus?

Meanwhile, I've added its installation to the Docker image.

Regards.

**Comment by j3ssie** [comment]
Thank you for reporting, I just fixed the option for that. It simply check cloud setup is okay or not which is a feature for premium package only.

**Comment by mablanco** [comment]
OK, I wasn't aware this is a premium feature. I understand that I should remove Packer from the Docker image, shouldn't I?

**Comment by j3ssie** [comment]
Yeah sure, to reduce the image size
