### ISSUE TITLE
error build

### ISSUE THREAD

**Issue by FIXERMAN** [j3ssie/osmedeus#226]
go: finding gopkg.in/yaml.v2 v2.2.1
go: finding github.com/google/go-querystring v1.0.0
go: error loading module requirements
make: *** [Makefile:6: build] Ошибка 1

как собрать?

**Comment by j3ssie** [comment]
Please be more specific and use English. If you have a hard time building the Osmedeus binaries, you can always get it at the  release page here: https://github.com/j3ssie/osmedeus/releases
