### ISSUE TITLE
cat: /home/mah3sec/.osmedeus/config.yaml: No such file or directory

### ISSUE THREAD

**Issue by Mah3Sec** [j3ssie/osmedeus#227]
cat: /home/mah3sec/.osmedeus/config.yaml: No such file or directory

**Comment by j3ssie** [comment]
Please be more specific, give some more information like what command you ran? what is your OS? 
And please read the FAQs page first: https://docs.osmedeus.org/faq/ Your issue might happen when you install on root but run on normal user.
