### ISSUE TITLE
Spider 0 Links

### ISSUE THREAD

**Issue by anasbousselham** [j3ssie/osmedeus#229]
Hi,
I have 0 Links and empty file when I use spider module, the gospider is present in the binary directory  : 
![image](https://user-images.githubusercontent.com/9357948/157120206-47685da2-f96b-415f-9871-437ad06e3d23.png)

**Comment by j3ssie** [comment]
It's simply that there's no vulnerability. It very much depends on your target.
You can check some similar questions here: https://docs.osmedeus.org/faq/

**Comment by j3ssie** [comment]
It's simply that there's no vulnerability. It very much depends on your target.
You can check some similar questions here: https://docs.osmedeus.org/faq/
