### ISSUE TITLE
Can not login when delopy Osmedeus on vps

### ISSUE THREAD

**Issue by 1hack0** [j3ssie/Osmedeus#23]
<img width="1194" alt="IMG150" src="https://user-images.githubusercontent.com/22652878/56664651-0b99a380-66db-11e9-99e8-da3fea522271.png">

As you can see,  the request url is http://127.0.0.1:5000/api/auth. I think it should request http://vps-ip/api/auth. How can i fix the issue?

**Comment by j3ssie** [comment]
By default, you can only run Osmedeus on localhost which means you need to ssh on VPS and do a tmux or screen to run it.
If you really wanna do remote access check out protips this wiki page for more [detail](https://github.com/j3ssie/Osmedeus/wiki/REST-API#security-concern).

**Comment by 1hack0** [comment]
Hi @j3ssie,

I use  ssh forwarding using this command.
```
ssh -L 5000:localhost:5000 root@vps-ip
```

Now I can access http://localhost:5000, but still cann't login. The url request is still http://127.0.0.1:5000/api/auth and 127.0.0.1 can't be accessed. I have no idea how to solve it.

<img width="1079" alt="WechatIMG151" src="https://user-images.githubusercontent.com/22652878/56714561-c079a200-6767-11e9-90b7-ad81ce5f8e91.png">

Thanks,

Richard

**Comment by j3ssie** [comment]
sorry for my typo on ssh command on the wiki. Your command is right
```
ssh -L 5000:localhost:5000 root@vps-ip
```
But you need to make sure enable `GatewayPorts yes` in your `/etc/ssh/sshd_config`.
I just test it on my machine and it works perfectly.
Can you using `netstat` or something to check port 5000 is open on your local machine?

![Screen Shot 2019-04-25 at 17 29 27](https://user-images.githubusercontent.com/23289085/56729680-0fcbcc80-6780-11e9-9fd9-4129cf493cdc.png)

**Comment by 1hack0** [comment]
I request http://localhost:5000/api/auth, it works . But i request http://127.0.01:5000/api/auth, and it fails.
<img width="1099" alt="WX20190425-185951@2x" src="https://user-images.githubusercontent.com/22652878/56731194-79ea6e80-678c-11e9-9bb3-27f53fb35a86.png">
<img width="1105" alt="WX20190425-190045@2x" src="https://user-images.githubusercontent.com/22652878/56731196-79ea6e80-678c-11e9-91f1-ffeab4a1dc76.png">

**Comment by 1hack0** [comment]
When i click login button, it will request http://127.0.01:5000/api/auth, rather than  http://localhost:5000/api/auth. So it can not login successfully..
![1556190388739](https://user-images.githubusercontent.com/22652878/56731520-43612380-678d-11e9-8739-f79738aeb878.jpg)

**Comment by j3ssie** [comment]
It’s really weird. Could you try ssh command but with 127.0.0.1 instead of localhost.

**Comment by 1hack0** [comment]
i try  this ssh command.
```
ssh -L 5000:127.0.0.1:5000 root@207.148.120.60. 
```
It still doesn't work. Is there any way to change the request url ( http://127.0.01:5000/api/auth) to http://localhost:5000/api/auth?

**Comment by 1hack0** [comment]
Hi @j3ssie ,

I solve it when I change to other local machine(Ubuntu). I don't know what's wrong with my previous machine(Mac OS).

Thanks,

Richard Cao

**Comment by j3ssie** [comment]
> i try this ssh command.
> 
> ```
> ssh -L 5000:127.0.0.1:5000 root@207.148.120.60. 
> ```
> It still doesn't work. Is there any way to change the request url ( http://127.0.01:5000/api/auth) to http://localhost:5000/api/auth?

It’s hardcode on the react UI. I’ll add an option to change it on the next release.

**Comment by j3ssie** [comment]
@1hack0 Just commit an option to change API destination could you give it a try.
See more [details](https://github.com/j3ssie/Osmedeus/wiki/How-does-it-work).

**Comment by 1hack0** [comment]
Thank you
