### ISSUE TITLE
Adding nrich

### ISSUE THREAD

**Issue by tequreq** [j3ssie/osmedeus#230]
https://gitlab.com/shodan-public/nrich

**Comment by j3ssie** [comment]
I prefer to scan with real-time data so didn't think it fit the workflow but you feel free to customize one with [sdlookup](https://github.com/j3ssie/sdlookup) which is a golang version of nrich.

here how you can do it: https://docs.osmedeus.org/workflow/customize-your-own-workflow/

**Comment by j3ssie** [comment]
I prefer to scan with real-time data so didn't think it fit the workflow but you feel free to customize one with [sdlookup](https://github.com/j3ssie/sdlookup) which is a golang version of nrich.

here how you can do it: https://docs.osmedeus.org/workflow/customize-your-own-workflow/
