### ISSUE TITLE
Multi-target Workspace Names are scattered, but they are actually one organization

### ISSUE THREAD

**Issue by zhihuba** [j3ssie/osmedeus#231]
# Multi-target Workspace Names are scattered, but they are actually one organization
## Suppose there is a file to be scanned whose content is(from ssl certificate)
- paypal.com
- paypal.me
- venmo.com
- py.pl
# commands
```bash
osmedeus scan -f cidr -T tag.txt
```
Multiple directories will be generated under the /root/.osmedeus/workspaces directory. **_Ideally should be that there is only one paypal.com contains all subdirectory_**
The following is a screenshot of the local test

![image](https://user-images.githubusercontent.com/22538559/163659817-d02fb318-d8af-4684-a232-75185d6e8fd9.png)

**Comment by j3ssie** [comment]
First of all, this is the intended output. Each line in your `-T input-file.txt` will store in a folder like that.
If you really want all of your output stored in 1 folder then use `osmedeus scan -f cidr -T tag.txt -W /tmp/my-custom-workspaces/`

**Comment by j3ssie** [comment]
First of all, this is the intended output. Each line in your `-T input-file.txt` will store in a folder like that.
If you really want all of your output stored in 1 folder then use `osmedeus scan -f cidr -T tag.txt -W /tmp/my-custom-workspaces/`

**Comment by BitThr3at** [comment]
is i am doing something wrong here? it is not creating custom workspace
Command used - `osmedeus scan -f test -T targets.txt  -W /root/CAS/ `

![image](https://github.com/j3ssie/osmedeus/assets/45028933/2b359a06-d4fd-4234-b6ff-e2e811529be0)
