### ISSUE TITLE
Osmedeus v4.1.1 using full disk at subdomain scanning

### ISSUE THREAD

**Issue by s41n1k** [j3ssie/osmedeus#233]
Hi,
The osmedeus latest version uses full disk for subdomain scan. At the step of subdomain scanning, huge results generate and save into `final-subdomain` files. The scanning process runs until the disk is full.
Please check out this urgently.

I am using the pro version.

![osmedeus](https://user-images.githubusercontent.com/64774009/169504271-87ca5d03-7f7e-4a2a-9ded-1951d8f0f3d1.png)

**Comment by j3ssie** [comment]
Thank you for reporting this, this is actually the expected result since it does permutation subdomain enumeration with goaltdns and str-replace.

I just update a new workflow with the options to disable it like this 
`osmedeus scan -f extensive -t sample.com -p 'enablePermutation=false'`

**Comment by s41n1k** [comment]
I try `osmedeus scan -f extensive -t target.com -p 'enablePermutation=false'` this command but still same result.

**Comment by x1aochuan** [comment]
this is a file  "probing.yaml"
