### ISSUE TITLE
how can i change the port after installing 

### ISSUE THREAD

**Issue by Fawadkhanfk** [j3ssie/osmedeus#234]
[2022-06-01T02:23:48] ERROR error create ssl listener: listen tcp 0.0.0.0:8000: bind: address already in use
[+] Web UI available at: http://0.0.0.0:8000/ui/
2022/06/01 02:23:48 listen tcp4 0.0.0.0:8000: bind: address already in use

**Comment by khiemdoan** [comment]
You can set `port` flag to change the port to listen, eg:

```bash
osmedeus server --port 9000
```

**Comment by Fawadkhanfk** [comment]
thank you
