### ISSUE TITLE
UI display issues

### ISSUE THREAD

**Issue by patrickhener** [j3ssie/osmedeus#235]
![issue](https://user-images.githubusercontent.com/7579055/177982991-fe0c8a60-e5c5-461c-af27-5cbb94122f4d.png)

The image shows that one of my scans in the list is already done. But then the ones after it in the list also are displayed as done, where they clearly are not.

So this is a display issue, a bug.

Regards,
Patrick

**Comment by disclaimer8** [comment]
Same for me

**Comment by d4op** [comment]
the server ui for the webinterface should be improved in the next releases i hope.
great tool.

**Comment by void-ll** [comment]
Same for me

**Comment by j3ssie** [comment]
A fresh installation should resolve the issue and make it work properly now.
