### ISSUE TITLE
Password not working

### ISSUE THREAD

**Issue by pixelnull** [j3ssie/Osmedeus#24]
Looking at the template-conf.conf file I was able to change the user and password.

But when I start the scan and try to access the server the new password doesn't work. I did try with the default "super_secret_ too but that also didn't work.

Am I doing something wrong or is there a known bug?

Thanks

**Comment by j3ssie** [comment]
If you're not custom anything it's should be in `core/config.conf`.
Check out this wiki page for more [detail](https://github.com/j3ssie/Osmedeus/wiki/REST-API#get-the-jwt-token)
