### ISSUE TITLE
Command 'shopt' not found

### ISSUE THREAD

**Issue by francescouk** [j3ssie/osmedeus#241]
Hello there,
I would like to know if this is really an issue or to finish the osmedeus installation I need to run this command?

```
Run source ~/.bashrc  to complete the install
```

```
Command 'shopt' not found, did you mean:
  command 'shout' from deb libshout-tools
Try: apt install <deb name>
```

Thanks for the attention

**Comment by j3ssie** [comment]
There no `shopt` tools in Osmedeus. It must be something wrong with your machine.
