### ISSUE TITLE
cloud scanning failed

### ISSUE THREAD

**Issue by 0xjson** [j3ssie/osmedeus#242]
### environment: WSL2 ubuntu-22.04

regenerated ssh key and placed it in ```~/osmedeus-base/cloud/ssh/``` folder

![Screenshot 2022-12-18 044318](https://user-images.githubusercontent.com/61111746/208265614-c9eb3cfc-fdda-4e87-89c4-e9b3ad42fab1.png)

rebuild snapshot error

![Screenshot 2022-12-18 043918](https://user-images.githubusercontent.com/61111746/208265694-7efcb63f-dc50-470e-a46f-8c663b75fb7a.png)

keep getting ```process exited with status 127```

so far, everything else's functioning fine. I'm able to do local scans, just that I'm facing this weird issue.  
i'm using the premium version

**Comment by j3ssie** [comment]
This should fix with the latest release, update your premium package and try it again then.
