### ISSUE TITLE
GenNucleiReport Not Working

### ISSUE THREAD

**Issue by xhzeem** [j3ssie/osmedeus#244]
Hi,

I'm not able to generate a nuclei report, in the debug it shows that it worked, but the report is always empty :/ 

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/34074156/214965747-22c13a76-7cc6-4ad0-aea9-10ccf4bcfa48.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/34074156/214965688-d9981983-0362-4884-b767-3f64805637e3.png">

**Comment by j3ssie** [comment]
A fresh installation should resolve the issue and make it work properly now.
you can run the command `rm -rf ~/.osmedeus ~/osmedeus-base` then run the install script again
