### ISSUE TITLE
WARN Your module portscan doesn't exist

### ISSUE THREAD

**Issue by Aviksaikat** [j3ssie/osmedeus#247]
![image](https://user-images.githubusercontent.com/31238298/221853223-f1a43784-ae74-469f-82a3-47128882df99.png)
cmd:
```sh
osmedeus scan -f portscan -t aol.com
```

**Comment by mnematolahi** [comment]
It is not module, it is workflow. It seems the defined workflow is not in your path or it is empty. Check portscan.yaml. it must have following code: 

name: portscan
desc: Scanning for subdomain

params:
  - testData: "~/go/src/github.com/j3ssie/osmedeus/test-data"

steps:
  # get data from cdn
  - scripts:
      - ImportPortJson("{{testData}}/{{Workspace}}/portscan/portscan-json.txt")

**Comment by mnematolahi** [comment]
And also if your scan stuck at portscan:

It will stay there because it got a sudo password prompt. Some special tools require root permission to run like nmap. Make sure you allow nmap can be run without sudo password prompt.

**Comment by j3ssie** [comment]
You're running the wrong command.
The correct command should be `osmedeus scan -m cidr-probing -t list-of-cidr.txt` or `osmedeus scan -f cidr -t list-of-cidr.txt`
