### ISSUE TITLE
ReadingLines() function fails with 'bufio.Scanner: token too long' error on large line data

### ISSUE THREAD

**Issue by c0r1** [j3ssie/osmedeus#248]
Hi,

When I run Rustscan for port scanning, some IPs return a large number of open ports. As a result, the generated raw-open-ports.txt file looks like the following:

![image](https://user-images.githubusercontent.com/35213328/226390044-1459c0ed-11bf-4f5f-88e0-929167163710.png)

However, when I run CleanRustScan() to process the above raw-open-ports.txt file, I noticed that the [function](https://github.com/j3ssie/osmedeus/blob/6d49707fd69da96a4bd88bbf10b43758c10c7f39/utils/helper.go#L159:6) throws a `"bufio.Scanner: token too long"` error when processing some very large line data.

Therefore, I suggest setting the maximum token size in the `scanner.Buffer()` function's second parameter to support reading files with very large line data. For example, you can use the following code:

```Golang
scanner := bufio.NewScanner(file)
scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
for scanner.Scan() {
    val := strings.TrimSpace(scanner.Text())
    if val == "" {
        continue
    }
    result = append(result, val)
}
```

**Comment by j3ssie** [comment]
Thanks for raising the issue. I've pushed an updated version that addresses the problem you mentioned.
