### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by Mr-xn** [j3ssie/osmedeus#25]
- IP proxy pool to confront so many WAF 
- Web Ui Submit task[lists]

**Comment by j3ssie** [comment]
Already on the todo list :)

**Comment by helifen185** [comment]
添加Web Ui提交任务后的工作进度，有任务进度详情就更棒了
Adding Web Ui's work schedule after submitting a task makes it even better to have details of the progress of the task.

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
