### ISSUE TITLE
There is a problem with the delete interface in the ui

### ISSUE THREAD

**Issue by void-ll** [j3ssie/osmedeus#252]
It seems that I forgot to write the delete interface at the delete function
<img width="721" alt="Screenshot 2023-06-01 at 21 16 36" src="https://github.com/j3ssie/osmedeus/assets/40752745/33fff26d-0fd3-4fde-99ce-aad38e7adf8e">
It seems that I forgot to write the delete interface in the delete function, and there is also a problem with the display, I hope it can be solved, thank you

**Comment by j3ssie** [comment]
I appreciate you bringing it to my attention. In response, I have included the delete button in the most recent update.
