### ISSUE TITLE
ModuleNotFoundError: No module named 'flask'

### ISSUE THREAD

**Issue by kamoteroot** [j3ssie/Osmedeus#26]
[*] New config file created: core/config.conf
--~~~=:>[ Starting Flask API ]>
Traceback (most recent call last):
  File "core/app.py", line 15, in <module>
    from flask import abort
ModuleNotFoundError: No module named 'flask'
[+] Make new directory: /home/kitsploit/osmedus/Osmedeus/workspaces/example.net
[-] Fail to set config, Please check Flask API !!!
root@kali:/home/kitsploit/osmedus/Osmedeus# sudo pip install flask
Requirement already satisfied: flask in /usr/lib/python2.7/dist-packages (1.0.2)

**Comment by j3ssie** [comment]
It's required python3 so please do pip3 and make sure you're already run `install.sh`.
