### ISSUE TITLE
libc6 library version in docker image isn't supported by Katana

### ISSUE THREAD

**Issue by Cydriin** [j3ssie/osmedeus#269]
The docker image has versions of libc6 that aren't supported by Katana. 

```
katana: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by katana)
katana: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by katana)
```

```
ldd --version
ldd (Debian GLIBC 2.28-10) 2.28
```

After running `apt update`
The Debian Buster apt repository doesn't have the versions required by Katana available.

```
apt list -a libc6
Listing... Done
libc6/oldoldstable 2.28-10+deb10u2 amd64 [upgradable from: 2.28-10]
libc6/oldoldstable 2.28-10+deb10u1 amd64
libc6/now 2.28-10 amd64 [installed,upgradable to: 2.28-10+deb10u2]
```

**Comment by j3ssie** [comment]
I've made changes to the foundational image used for creating the Osmedeus image. You can either commence the image building process anew or simply pull the most recent Docker image, and it should function correctly.
