### ISSUE TITLE
[-] Fail to set config, Please check Flask API !!!

### ISSUE THREAD

**Issue by evilwing** [j3ssie/Osmedeus#27]
app is running
![image](https://user-images.githubusercontent.com/25416365/56867845-0d39d300-6a1d-11e9-9c76-7a60c2d85f74.png)
![image](https://user-images.githubusercontent.com/25416365/56867846-16c33b00-6a1d-11e9-874d-98ef7c1bde32.png)
![image](https://user-images.githubusercontent.com/25416365/56867849-1b87ef00-6a1d-11e9-922e-379b8e2c00f7.png)

**Comment by evilwing** [comment]
I solved this problem, but the operation is still wrong.

requests.exceptions.InvalidHeader: Value for header {Authorization: False} must be of type str or bytes, not <class 'bool'>

![image](https://user-images.githubusercontent.com/25416365/56867877-bb457d00-6a1d-11e9-8a45-cf592cc125c6.png)

**Comment by j3ssie** [comment]
Seem that you can’t get the JWT to send the request.
Could you just run the Flask API by this command `python3 core/app.py` and try to get JWT manually using curl or something like that.
More [detail](https://github.com/j3ssie/Osmedeus/wiki/REST-API#get-the-jwt-token)

**Comment by evilwing** [comment]
![image](https://user-images.githubusercontent.com/25416365/56876214-700c8800-6a78-11e9-994b-d7fef857e5e3.png)
right?
This is the wiki method,it is  error.

![image](https://user-images.githubusercontent.com/25416365/56876255-b2ce6000-6a78-11e9-8fb9-233f72eb7c5b.png)

![image](https://user-images.githubusercontent.com/25416365/56876227-8286c180-6a78-11e9-8380-5bc72e33f73a.png)

**Comment by evilwing** [comment]
![image](https://user-images.githubusercontent.com/25416365/56876492-4ce2d800-6a7a-11e9-9115-705bdbc27110.png)

**Comment by j3ssie** [comment]
Yeah you can only set the config from localhost and get the JWT via `/api/auth` endpoint.
So maybe you mess up something that the client can't get the JWT.
could you stop the server, clone it and install again then run `./osmedeus.py -t example.com` to give me more detail.

**Comment by evilwing** [comment]
I am bothering you, I can do it here, thank you.

**Comment by j3ssie** [comment]
Never mind, maybe I’m gonna make a tutorial video for installation :)
