### ISSUE TITLE
Add support for ARM64

### ISSUE THREAD

**Issue by pak0s** [j3ssie/osmedeus#273]
Can you please add support for ARM64? The binaries installed are x86 and therefore won't work in ARM64.

I am testing in a kali vm arm64 image on MAC m3.

**Comment by j3ssie** [comment]
Hi, I just put the release binary for it. You can install the on an ARM machine via the macOS install script like below
```
bash <(curl -fsSL https://raw.githubusercontent.com/osmedeus/osmedeus-base/master/install-macos.sh)
```
