### ISSUE TITLE
环境配置完毕后一直出现这个？

### ISSUE THREAD

**Issue by just805** [j3ssie/Osmedeus#28]
![微信截图_20190429123441](https://user-images.githubusercontent.com/18697510/56876620-51f45700-6a7b-11e9-9d34-2cd272c86a3c.png)
 * Logging: off
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
PS：系统kali-Linux

**Comment by j3ssie** [comment]
What are you trying to say? See this [architecture](https://github.com/j3ssie/Osmedeus/wiki/How-does-it-work) for more detail.

Please, read a README for basic usage and The wiki for [advanced usage](https://github.com/j3ssie/Osmedeus/wiki/Advanced-Usage).
