### ISSUE TITLE
Problem running this remotely

### ISSUE THREAD

**Issue by abdilahrf** [j3ssie/Osmedeus#29]
i tried to run this remotely using

`python3 core/app.py -b 0.0.0.0 -p 5000`

and change `core/config.conf` into:
```
[Server]
username = secret
password = secret
remote_api = http://0.0.0.0:5000
```

but the web still send request into 127.0.0.1 api

**Comment by j3ssie** [comment]
Currently, a lot of APIs only allow local access and will be officially supported on the next release.

So meanwhile check out this [wiki](https://github.com/j3ssie/Osmedeus/wiki/REST-API#security-concern) for access remote through SSH.

**Comment by abdilahrf** [comment]
Okay got it, i was able to access remotely using forwarding to my 127.0.0.1
