### ISSUE TITLE
Issue with setup tools curl

### ISSUE THREAD

**Issue by NakToHak** [j3ssie/Osmedeus#30]
Error:
setuptools.sandbox.UnpickleableException: ConfigurationError('Could not run curl-config: [Errno 2] No such file or directory',)
OS: Linux Mint 19.1

**Comment by j3ssie** [comment]
So what did you run to cause this error.
Make sure you follow this [wiki](https://github.com/j3ssie/Osmedeus/wiki/Installation) non-kali install

**Comment by NakToHak** [comment]
I am running Linux Mint 19.1. All I did was:
Git Clone...
cd into it...
./install.sh..
Everything was fine until the ./install.sh part. It threw a bunch of "Permission denied" so I sudo the install file "sudo ./install.sh" and it runs fairly normal till it gets to flask.
Error: 
Collecting flask_jwt
  Downloading https://files.pythonhosted.org/packages/9b/8a/5d3b2e593f1fc5c1b464aa1cbf35023a4400a2b53ce6a52801f68d7a1eeb/Flask-JWT-0.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bpya2nan/flask-jwt/

**Comment by j3ssie** [comment]
Basically sudo only need to run `sudo apt install -y something` and the rest is just normal user. If you run `sudo install.sh` then after the installation you can only using Osmedeus as root user.

And look like you're using python 2 so could install setuptools manually for python 3 by using this command.
```
sudo apt-get install python3-setuptools
```

**Comment by j3ssie** [comment]
Consider the bug have been fixed because not get a response since 17 days.
