### ISSUE TITLE
After waiting for a few hours, it has been Waiting for PortScan module

### ISSUE THREAD

**Issue by bowu678** [j3ssie/Osmedeus#31]
Response: | Success:               | Total:
OK:       |            0 (  0.00%) |            0 (  0.00%)
NXDOMAIN: |            0 (  0.00%) |            0 (  0.00%)
SERVFAIL: |            0 (  0.00%) |            0 (  0.00%)
REFUSED:  |            0 (  0.00%) |            0 (  0.00%)
FORMERR:  |            0 (  0.00%) |            0 (  0.00%)
[*] Waiting for PortScan module

Unable to complete all work

**Comment by j3ssie** [comment]
Osmedeus support Continuous scan so you just have to Ctrl+C and run exactly your previous command it's gonna resume the scan.

For the error, could verify for me that file `final-IP-TARGET.txt` or `final-TARGET.txt` is exist because that file required to run PortScan module.

**Comment by sumgro** [comment]
I've been facing the same error and it gets stuck at Waiting for PortScan module. As for the above files you mention, only final-IP-TARGET.txt is available, not the final-TARGET.txt.

Here is the error message:

[*] Waiting for PortScan module

Starting masscan 1.0.4 (http://bit.ly/14GZzcT) at 2019-05-13 02:57:09 GMT
 -- forced options: -sS -Pn -n --randomize-hosts -v --send-eth
Initiating SYN Stealth Scan
Scanning 136 hosts [65536 ports/host]
[*] Waiting for PortScan module
[*] Waiting for PortScan module
[*] Waiting for PortScan module

**Comment by j3ssie** [comment]
Basically Portscan module gonna take `final-TARGET.txt` file or input file if this module run directly then resolve IP and `final-IP-TARGET.txt` file. So your case absolutely ordinary.

This scan may take really long time depending on your network because masscan gonna scan a bunch of hosts so it's not an error just it takes time to do.
