### ISSUE TITLE
Getting error in SubdomainScanning module

### ISSUE THREAD

**Issue by tanujjane** [j3ssie/Osmedeus#32]
--==[ Check the output: /home/ec2-user/Osmedeus/workspaces/reacted.com/subdomain/raw-reacted.com/-gobuster.txt
[+] Writing /home/ec2-user/Osmedeus/core/rest/storages/activities.json
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module

Resolving 0 Unique Hosts found

Total 0 Unique subdomains found for reacted.com/

--==[ Check the output: /home/ec2-user/Osmedeus/workspaces/reacted.com/subdomain/reacted.com/-subfinder.txt
[+] Writing /home/ec2-user/Osmedeus/workspaces/reacted.com/subdomain/std-reacted.com/-subfinder.std
[-] Writing fail: /home/ec2-user/Osmedeus/workspaces/reacted.com/subdomain/std-reacted.com/-subfinder.std
[+] Writing /home/ec2-user/Osmedeus/core/rest/storages/activities.json
[+] Unique result
[+] Writing /home/ec2-user/Osmedeus/workspaces/reacted.com/subdomain/final-reacted.com/.txt
[-] Writing fail: /home/ec2-user/Osmedeus/workspaces/reacted.com/subdomain/final-reacted.com/.txt
--~~~=:>[ Conclusion for SubdomainScanning ]>
Traceback (most recent call last):
  File "./osmedeus.py", line 161, in <module>
    main()
  File "./osmedeus.py", line 157, in main
    parsing_argument(args)
  File "./osmedeus.py", line 77, in parsing_argument
    single_target(options)
  File "./osmedeus.py", line 97, in single_target
    routine.normal(options)
  File "/home/ec2-user/Osmedeus/core/routine.py", line 32, in normal
    subdomain.SubdomainScanning(options)
  File "/home/ec2-user/Osmedeus/modules/subdomain.py", line 26, in __init__
    self.conclude()
  File "/home/ec2-user/Osmedeus/modules/subdomain.py", line 112, in conclude
    with open(all_subdomain, 'r+') as s:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ec2-user/Osmedeus/workspaces/reacted.com/subdomain/final-reacted.com/.txt'

**Comment by j3ssie** [comment]
Osmedeus support Continuous scan so you just have to Ctrl+C and run exactly your previous command it's gonna resume the scan.

For your error which is look like subdomain module can't find any subdomain so It's gonna fail to unique the results.
Could you try another target and give me some feedback again.

**Comment by tanujjane** [comment]
But I found subdomain on the same domain with knock, aquatone, fierce, amass and other.

**Comment by j3ssie** [comment]
It's really weird. So when Osmedeus run it prints out [*] Execute: `very long command here`.
Could you try that manually to make sure it works and give me more information?

**Comment by tanujjane** [comment]
I tried ./osmedeus.py -m subdomain -t example.com 
Getting this error

*] Config file detected: core/config.conf
--~~~=:>[ Starting Flask API ]>
Traceback (most recent call last):
  File "./osmedeus.py", line 161, in <module>
    main()
  File "./osmedeus.py", line 157, in main
    parsing_argument(args)
  File "./osmedeus.py", line 51, in parsing_argument
    options = config.parsing_config(config_path, args)
  File "/home/ec2-user/Osmedeus/core/config.py", line 329, in parsing_config
    with open(config_path, 'w') as configfile:
PermissionError: [Errno 13] Permission denied: 'core/config.conf'
 * Logging: off
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off

**Comment by j3ssie** [comment]
Look like you need sudo permission for that?
Anyway just DM me via @j3ssiejjj for quickly resolve this.

**Comment by tanujjane** [comment]
Great, it's working now. I just reinstall and use sudo.

Thanks for the support and the great tool.

**Comment by j3ssie** [comment]
Yeah, thank you for the feedback.

**Comment by chinni8899** [comment]
Error is getting i try different domains it showing these errors
[] Waiting for SubdomainScanning module
[] Waiting for SubdomainScanning module
[] Waiting for SubdomainScanning module
[] Waiting for SubdomainScanning module
