### ISSUE TITLE
All python3 package installed ok, still got error "Fail to set config, Something went from with Flask API !!!" 

### ISSUE THREAD

**Issue by taegukusa** [j3ssie/Osmedeus#35]
python3 core/app.py   Runs ok 

 * Logging: off
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off

But still get error, when run "python3 osmedeus.py  -t google.com"

[*] Config file detected: core/config.conf
--~~~=:>[ Starting Flask API ]>
 * Logging: off
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
[-] Fail to set config, Something went from with Flask API !!!
[-] Visit this page for common issue: https://github.com/j3ssie/Osmedeus/wiki/Common-Issues
 
What's  the matter ?

**Comment by j3ssie** [comment]
After running this command `python3 core/app.py` could you access `https://127.0.0.1:5000` vi browser or curl.

If you can just do an [authentication](https://github.com/j3ssie/Osmedeus/wiki/REST-API#get-the-jwt-token) process manually to make sure you're config them right.

**Comment by taegukusa** [comment]
After running  "python3 core/app.py" and  access https://127.0.0.1:5000 vi browser
I can get :

 * Logging: off
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 ERROR in app: Exception on /api/auth [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/tgk/test/github_tools/webscan/Osmedeus/core/rest/authentication.py", line 44, in post
    if username == options.get('USERNAME'):
AttributeError: 'NoneType' object has no attribute 'get'

My core/config.conf file:

[Enviroments]
cwd = /tmp/demo/Osmedeus
workspaces = ${CWD}/workspaces/
workspace = ${CWD}/workspaces/google.com
plugins_path = ${CWD}/plugins
go_path = ${CWD}/plugins/go
healthcheck = False
github_api_key = None

[Resources]
directory_full = ${Enviroments:plugins_path}/wordlists/dir-all.txt
domain_full = ${Enviroments:plugins_path}/wordlists/all.txt
domain_short = ${Enviroments:plugins_path}/wordlists/shorts.txt

[Server]
username = Osmedeus
password = MFWPLM
remote_api = https://127.0.0.1:5000

[Slack]
local_name = JJ
bot_token = None
log_channel = None
log_name = logcmd
status_channel = None
status_name = status
stds_channel = None
stds_name = stds
report_channel = None
report_name = report
verbose_report_channel = None
verbose_report_name = verbose-report

[Mode]
speed = quick
module = None
debug = False
force = False

[Proxy]
proxy = None
proxy_file = None
proxy_cmd = proxychains -f None

[Target]
target = google.com
target_list = None
company = google.com
strip_target = google.com
git_target = None
burpstate_target = None
ip = 216.58.199.14
output = google.com
more =
input = None

**Comment by taegukusa** [comment]
It runs ok now, all because of i used a proxy

Thank you !

**Comment by j3ssie** [comment]
Yeah maybe the client can't send an authen because of your proxy.
And btw the proxy not work really well this time.

**Comment by lorenzoromani1983** [comment]
I am having the same problem as above. Trying to run with Kali on Vmware.
