### ISSUE TITLE
Actions doesn't work

### ISSUE THREAD

**Issue by Senanfurkan** [j3ssie/Osmedeus#36]
In the Summary tab, near the subdomains 'EDIT' & 'DETAILS' buttons are not working. 
![actions](https://user-images.githubusercontent.com/33626136/58074279-915f2080-7bad-11e9-856f-08fd72b2d137.png)

**Comment by j3ssie** [comment]
Yeah, that's just placeholder button. So currently it doesn't do anything.
More features will come with this :).
