### ISSUE TITLE
Nothing to show

### ISSUE THREAD

**Issue by Phoenix1112** [j3ssie/Osmedeus#37]
hello.. thanks for this project... i can not see results on web gui screen... 
![osmedeus](https://user-images.githubusercontent.com/42475284/58545376-ca317200-820b-11e9-9311-b5a2c62da44b.png)

**Comment by j3ssie** [comment]
That's simply because no modules were complete.

**Comment by Phoenix1112** [comment]
tomorrow video will be ready.

https://www.youtube.com/c/teknolojivesavunma

**Comment by Phoenix1112** [comment]
osmedeus been scanning for 6 hours... still continues... I'm going to bed soon... I'm just scanning for gitlab...The gitlab site does not have too many subdomains.. There may not be a total of 50.. but the scan is over 6 hours..I stopped it now... if I start the program again tomorrow, will continue where it left off?
