### ISSUE TITLE
LOGIN

### ISSUE THREAD

**Issue by ximiluliyi** [j3ssie/Osmedeus#39]
What is the login password for 127.0.0.1:5000?

**Comment by j3ssie** [comment]
If you're not custom anything it's should be in `core/config.conf`.
Check out this wiki page for more [detail](https://github.com/j3ssie/Osmedeus/wiki/Web-UI)

**Comment by ximiluliyi** [comment]
> 如果你没有定制它应该是什么`core/config.conf`。
> 查看此Wiki页面以获取更多[详细信息](https://github.com/j3ssie/Osmedeus/wiki/Web-UI)

My configuration is as follows:
/core/config.conf
[Server]
username = Osmedeus
password = Osmedeus
remote_api = https://127.0.0.1:5000

Still can't log in in the background, when logging in: incorrect credentials

**Comment by ximiluliyi** [comment]
![image](https://user-images.githubusercontent.com/40221289/59183383-6b221480-8b9e-11e9-9d69-2dda17da738a.png)

**Comment by ximiluliyi** [comment]
![image](https://user-images.githubusercontent.com/40221289/59183416-7c6b2100-8b9e-11e9-9159-a63cea41b575.png)

**Comment by j3ssie** [comment]
The actual credential on the server side a store in `Osmedeus/core/rest/storages/` folder. Just look for `options.json` file in that.

Credentials in `core/config.conf` file is used to login from client. It's will update that password next time you run `./osmedeus.py -t example.com ...` by calling Config API endpoints.

**Comment by j3ssie** [comment]
Due to Osmedeus upgraded into v2.0, this issue is no longer exist.
Please use the new version and send me a feedback.
Thank you.
