### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by sudomodesuperlearner** [j3ssie/Osmedeus#4]
![osmedeus_error1](https://user-images.githubusercontent.com/42622952/50984422-7675f480-14c7-11e9-966d-cee9138309f0.png)
This error occurs when I try to install and update. Could you please show me how to fix it?

**Comment by sudomodesuperlearner** [comment]
Disregard please. I already know how to fix it.

**Comment by j3ssie** [comment]
I should be fixed now.
Sorry for this typo.
