### ISSUE TITLE
Directory brute force tool

### ISSUE THREAD

**Issue by theblackturtle** [j3ssie/osmedeus#40]
Hi, I think `dirble` is better than `dirsearch` in directory brute force. It writes in Rust, so it's performance is excellent, and it has many futures than `dirsearch` too.

Github link: https://github.com/nccgroup/dirble

**Comment by j3ssie** [comment]
I've already heard about it, definitely test it out.
Thank you for the mention !

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
