### ISSUE TITLE
Hanging portscan with connection reset to flask

### ISSUE THREAD

**Issue by lmcthbe** [j3ssie/Osmedeus#43]
Hi,

After installing Osmedeus 1.4 on latest Kali. 

Any scan is hanging and UI is not accessible

tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      3754/python3  
$ curl http://127.0.0.1:5000
curl: (56) Recv failure: Connection reset by peer

![Screen Shot 2019-07-10 at 09 14 36](https://user-images.githubusercontent.com/1301592/60972150-af1a4d80-a2f3-11e9-97d2-8d2020e983f7.png)

**Comment by lmcthbe** [comment]
Found that UI is working much better with HTTPS :-)

**Comment by j3ssie** [comment]
Yeah, Flasks API still running because you ran as normal mode just in case we want  to view the result from UI.
It'll stop if you run Osmedeus in [remote way](https://github.com/j3ssie/Osmedeus/wiki/Remote-Setup).

**Comment by j3ssie** [comment]
Due to Osmedeus upgraded into v2.0, this issue is no longer exist.
Please use the new version and send me a feedback.
Thank you.
