### ISSUE TITLE
./osmedeus.py -m vuln -I / large databases, hanging, web ui?

### ISSUE THREAD

**Issue by thistehneisen** [j3ssie/Osmedeus#46]
If the -I database contains big list of several /24 IP addresses, has it been tested and working well? Also, what is the best way to see the results in the end and search through them, compare them? Through this command, the :5000 port doesn't seem to be open on the host, neither did I find how to open the web service in documentation.

Thanks!

**Comment by j3ssie** [comment]
Yeah, the UI only updated when the command is done.
And the best way to search is using command line with workspace folder of that target.
Anyway I’m planning to add a way to easily to view result and logging every section.

Just give me more screenshots or dm me @j3ssiejjj on twitter.

**Comment by j3ssie** [comment]
Due to Osmedeus upgraded into v2.0, this issue is no longer exist.
Please use the new version and send me a feedback.
Thank you.
