### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not bool

### ISSUE THREAD

**Issue by laohanme** [j3ssie/Osmedeus#48]
I think there have something callback error 
![Screenshot 2019-07-16 at 4 22 14 pm](https://user-images.githubusercontent.com/18119268/61278092-1c434c80-a7e6-11e9-9743-3c761653d28b.png)

**Comment by OllysCoding** [comment]
Getting the same error

**Comment by j3ssie** [comment]
It looks like the subdomain scan module may fail or didn't find any result.

**Comment by alexisab** [comment]
I've the same problem, the file `Osmedeus/workspaces/<your_target>/subdomain/final-<your_target>.txt` exists

**Comment by laohanme** [comment]
Yes the ``Osmedeus/workspaces/<your_target>/subdomain/final-<your_target>.txt`` was exists with the empty data

**Comment by crazywifi** [comment]
same issue..

**Comment by JoshuaMart** [comment]
Hi,
Same issue for me, I tried with installation on Ubuntu 18.04 & with docker installation (same error), the file `Osmedeus/workspaces/<your_target>/subdomain/final-<your_target>.txt` exists

**Comment by j3ssie** [comment]
Due to Osmedeus upgraded into v2.0, this issue is no longer exist.
Please use the new version and send me a feedback.
Thank you.
