### ISSUE TITLE
Run core/app.py as a deamon?

### ISSUE THREAD

**Issue by cybert79** [j3ssie/Osmedeus#49]
Hey, is it possible to run the app.py as a daemon started by init.d or systemctl?
(python3 app.py run gives an error that run is not reconized)

usage: app.py [-h] [-b BIND] [-p PORT] [--debug] [--nossl] [--remote]
app.py: error: unrecognized arguments: run

**Comment by j3ssie** [comment]
Currently no option for this but I normally running server persistent in `tmux` or `screen`.
Anyway, you could manually create init.d for this like any other program.

**Comment by cybert79** [comment]
[Unit]
Description=Osmedeus Service
After=network.target

[Service]
Type=simple
Restart=Always
ExecStart=/usr/bin/python3 /opt/Osmedeus/core/app.py -b 0.0.0.0 -p 5000

[Install]
WantedBy=multi-user.target
