### ISSUE TITLE
Can you explain the config.conf file?

### ISSUE THREAD

**Issue by cybert79** [j3ssie/Osmedeus#51]
Hey,

Can you add to the documentation an explanation of the config.conf file?
Maybe I can tweak it a bit.

**Comment by j3ssie** [comment]
Basically is a place to define some paths to store:
- Plugins and wordlists which is can be found [here](https://github.com/j3ssie/Osmedeus/blob/master/CREDITS.md).
- Define where to store the result of the scan and where to store **options.json** file which can consider is a database for Flask API.

Just DM me via [@j3ssie](https://twitter.com/j3ssiejjj) for any question.
