### ISSUE TITLE
Feature Request & Suggestions

### ISSUE THREAD

**Issue by ResistanceIsUseless** [j3ssie/osmedeus#52]
Been trying it out and so far I like the idea. I do feel like it's a bit of information overload and doesnt really help with parsing the information in a way to help you look for bugs. It might because mine freezes or takes too long and never finishes.  i really like the way that whatweb parses out the relevant information so it would be nice if you could find a way to do that as well as have it grab content using meg and parse out headers and any parameters found. I'm picturing two types of flows here. 1. Your currently flow that pretty much grabs everything with a more complete hierarchy of multiple steps based on findings. 2. A second more customized flow that allows you to create a custom hierarchy with either your own logic. Here is an example:
```
subfinder
 |----subjack
 |----assetfinder 
               |-----httprobe|whatweb (IP & DNS)
                             |-----fuff|gobuster
                             |         \----nikto (IP & DNS)
                             |                     \---- Logic (if URL contains X)
                             |                                 \----droopscan(IP & DNS)
                             |                                   \----wpscan(IP & DNS)
                             |-----meg
                                        |----nikto (IP & DNS)
                                        |----snallygaster (IP & DNS)
                                        |---- Logic (if URL contains X)
                                        |           \----droopscan(IP & DNS)
                                        |             \----wpscan(IP & DNS)
                                        |----proxy
                                        |           \----burp (IP & DNS)
                                        |----gf 

```
                             
Hopefully that makes sense, since you already have some logic in place but it would be nice to be able to customize by adding logic for more details actions as well as adding additional tools. other options might include.
- Checking robots.txt and robots meta tag for disallow paths and adding them to wordlists and scanning request and content enumeration. (Parsero could do some of this)
                                 

Also it might be nice to have the following tools as part of the modules:
snallygaster
nikto
whatweb
droopscan
parsero
fuff (to replace wfuzz)

I'm sorry for the long message and all the crazy ideas. If you would actually be interested in anything I mentioned and don't mind my intermediate python skills I'm always willing to chip in.  I've been working on my own version of reconscan(its a popular automation script for OSCP) which might also be helpful for enumeration of scanning services.

**Comment by r1nzler** [comment]
Damn it.. my markup didnt come through for the hierarchy, I'll try and sketch something up if you don;t get the general idea.

**Comment by j3ssie** [comment]
Thanks for your suggestion.

The main purpose of **Osmedeus** is discovering as much as target as possible and also find the potential target also. Anyway, I’m planning to add a way to easily to view result and logging every section.

Your idea is focussing on a single target which is I'm also planning to do more about it but currently, **Osmedeus** doesn't have a real DB so I considering to build a real DB for it or do it as a plugins for my new tool.

Just DM me via [@j3ssie](https://twitter.com/j3ssiejjj) for any question.

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
