### ISSUE TITLE
problem with slow speed mode

### ISSUE THREAD

**Issue by mohammed-sec2010** [j3ssie/Osmedeus#53]
hello

when I run the Osmedeous tool in slow mode, I see the osmedeous tool skip some tools like massdns and it uses a short dictionary  (see below pic)

command: python3 osmedeous.py -t bing.com -s 'All'

![Capture](https://user-images.githubusercontent.com/11797933/61447450-a4962e80-a959-11e9-8044-53f738723146.PNG)

**Comment by j3ssie** [comment]
Due to Osmedeus upgraded into v2.0, this issue is no longer exist.
Please use the new version and send me a feedback.
Thank you.
