### ISSUE TITLE
API keys

### ISSUE THREAD

**Issue by cybert79** [j3ssie/osmedeus#54]
I have seen that amass for example can use API keys form AlienVault, shodan, etc.
But I cannot find the config file to add them?

Is it in the config.conf you need to add them or do I need to create a config.ini file for it?

**Comment by j3ssie** [comment]
Well the main purpose of Osmedeus is you don't need to provide any API key but of course you can do it to get more result.

Normally **amass** will store in `Osmedeus/plugins/go/` so just put your config file for amass in that.
If amass command is need options to specify config file change it here `/Osmedeus/core/rest/storages/commands.json`

**Comment by jsypower** [comment]
I've just been looking at configuring the API keys for Amass - I am running mablanco/docker-osmedeus as per the README.md
I cannot seem to find the `commands.json` file you are talking about, @j3ssie 

Executing `find / -type f -iname commands.json` returns no relevant files.
Has this file been replaced with another?

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
