### ISSUE TITLE
'python3' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by rijinkcw** [j3ssie/Osmedeus#58]
←[1;32m--~~~=[  ←[1;36mStarting Flask API←[1;32m ]=~~~--
'python3' is not recognized as an internal or external command,
operable program or batch file.
←[1;34m[*]←[1;0m Loading config file from: C:\Users\root\.osmedeus\config.conf
←[1;31m[-]←[1;0m Fail to set config, Something went wrong with Flask API !
←[1;34m[*]←[1;0m Visit this page for common issue: https://github.com/j3ssie/Osm
edeus/wiki/Common-Issues

**Comment by j3ssie** [comment]
Make sure you install python3 and look likes you run it on Windows box which is Osmedeus not support yet.
Check out this [video](https://www.youtube.com/watch?v=kZ-uMC7c5OY&list=PLqpLl_iGMLnA6vbi1ZM-HmWLuedIP2PJl) for more detail.
