### ISSUE TITLE
How to run list of targets?

### ISSUE THREAD

**Issue by AdityaIndoori** [j3ssie/Osmedeus#59]
So I have a file with a list of domain names in every new line. How do I have it do reconnaissance on all of the domains in the file?

**Comment by j3ssie** [comment]
If you using normal mode the command should be `./osmedeus.py -T list_of_targets.txt`.
Or `-I  list_of_targets.txt` if you using direct mode.
More [detail](https://github.com/j3ssie/Osmedeus/wiki/Direct-Mode) about direct mode.
