### ISSUE TITLE
How to Run on VPS

### ISSUE THREAD

**Issue by d1pakda5** [j3ssie/osmedeus#61]
Hi
by default its run on 5000 on localhost but i wanted it to run on some port of my vps , how to do it

**Comment by j3ssie** [comment]
You may want to keep the server persistent by running the command below.

`python3 Osmedeus/core/app.py -b 0.0.0.0 -p 5000`

then you can run the client via **tmux** on that server or from your local machine.

Check this wiki for more [detail](https://github.com/j3ssie/Osmedeus/wiki/Remote-Setup)

**Comment by d1pakda5** [comment]
tried this but no success

**Comment by j3ssie** [comment]
Can you provide more detail about the error?

**Comment by getsec** [comment]
@d1pakda5  - Yes. Without the errors, we are pretty much in the water on this one, as the issue isn't with the project, it would be with your implementation.

**Comment by soupnatzi** [comment]
i have not tried to install it to my vps yet but was looking for more info on  this subject anyone?

**Comment by getsec** [comment]
@soupnatzi  - I have had no issues running it on my digital ocean droplet. The install procedure is the same. I dont understand what the issue could be as where you run the project shouldnt matter, unless you have some outbound security controls blocking you. If there is no more reply from the issue submitter this should be closed.

**Comment by soupnatzi** [comment]
hey @getsec i never said there was an issue just more info on the matter i have installed it yet like i said but thank you for letting me know everything its working fine for you with digital ocean.

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
