### ISSUE TITLE
Many Error on ./install

### ISSUE THREAD

**Issue by Dujunayan** [j3ssie/Osmedeus#62]
hey , 

is there any requirement before install ? i got many errors while installing  even i search on Google , i can't resolve it . like :

1- ERROR: requests-futures 1.0.0 requires futures>=2.1.3, which is not installed.
ERROR: jsparser 1.0 requires pycurl, which is not installed.
ERROR: safeurl 0.0.7 has requirement requests==2.7.0, but you'll have requests 2                                                                                        .22.0 which is incompatible.

2-  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0                                                                                        ] = '"'"'/tmp/pip-install-50qsxr1_/pycurl/setup.py'"'"'; __file__='"'"'/tmp/pip-                                                                                        install-50qsxr1_/pycurl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(                                                                                        __file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(com                                                                                        pile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-oszlakoh --                                                                                        python-tag cp35
       cwd: /tmp/pip-install-50qsxr1_/pycurl/
  Complete output (20 lines):
  Using curl-config (libcurl 7.52.1)
  Using SSL library: GnuTLS
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/curl
  copying python/curl/__init__.py -> build/lib.linux-x86_64-3.5/curl
  running build_ext
  building 'pycurl' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototype                                                                                        s -g -fdebug-prefix-map=/build/python3.5-3.5.3=. -fstack-protector-strong -Wform                                                                                        at -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPYCURL_VERSIO                                                                                        N="7.43.0.3" -DHAVE_CURL_SSL=1 -DHAVE_CURL_GNUTLS=1 -DHAVE_CURL_SSL=1 -I/usr/inc                                                                                        lude/python3.5m -c src/docstrings.c -o build/temp.linux-x86_64-3.5/src/docstring                                                                                        s.o
  In file included from src/docstrings.c:4:0:
  src/pycurl.h:168:30: fatal error: gnutls/gnutls.h: No such file or directory
   #   include <gnutls/gnutls.h>
                                ^
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pycurl
  Running setup.py clean for pycurl
Successfully built future

3-Traceback (most recent call last):
  File "core/app.py", line 128, in <module>
    app.run(host=host, port=port, debug=debug, ssl_context=(cert_path, key_path)                                                                                        )
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 1009,                                                                                         in run_simple
    inner()
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 962, i                                                                                        n inner
    fd=fd,
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 805, i                                                                                        n make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 723, i                                                                                        n __init__
    self.socket = ssl_context.wrap_socket(sock, server_side=True)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 611, i                                                                                        n wrap_socket
    **kwargs
  File "/usr/lib/python3.5/ssl.py", line 1077, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python3.5/ssl.py", line 699, in __init__
    self._context.load_cert_chain(certfile, keyfile)
TypeError: certfile should be a valid filesystem path
[*] Loading config file from: /root/.osmedeus/config.conf
[+] Make new directory: /root/.osmedeus/workspaces/example.com
[-] Fail to set config, Something went wrong with Flask API !
[*] Visit this page for common issue: https://j3ssie.github.io/Osmedeus/

**Comment by j3ssie** [comment]
May I ask what is your OS? And btw looks like you using **python 3.5** but Osmedeus required at least **python 3.6**

**Comment by j3ssie** [comment]
Due to Osmedeus upgraded into v2.0, this issue is no longer exist.
Please use the new version and send me a feedback.
Thank you.
