### ISSUE TITLE
where i can find osmedeus UI?

### ISSUE THREAD

**Issue by Shaz102** [j3ssie/Osmedeus#63]
i am searching for osmedeus UI and didn't find. is it you new jalaes project ?

**Comment by j3ssie** [comment]
I just update Osmedeus UI to https://github.com/jaeles-project/ui/tree/master/Osmedeus-ui
Just run 
```
yarn install
npm start
```
then you are good to go.

**Comment by thisEdgarMarquez** [comment]
Hello @j3ssie , I reopen this publication since the repository that contains the graphic interface is not the same version that currently manages the project and I would like to add some features. Thanks
