### ISSUE TITLE
Cannot dockerize v 1.5

### ISSUE THREAD

**Issue by mablanco** [j3ssie/Osmedeus#64]
Hi j3ssie. I'm trying to dockerize the newly released v 1.5 but I've found that at the end of the `install.sh` script you invoke Osmedeus like this:
```
python3 osmedeus.py --reset
```

This instruction prevents the `docker build` process to finish and, therefore, to build the image, as the Flask API stays running in the foreground. Therefore, I suggest that the `install.sh` script just finishes the installation of software without launching the process.

It seems that the `--reset` argument does some kind of initialization. Could it be invoked so it just does its tasks and then finishes the process?

Regards.

**Comment by j3ssie** [comment]
Just remove that line on install file. Will add it to first time run later.
Thank you for feedback.

**Comment by mablanco** [comment]
I had already done that in a test Dockerfile and it seemed to work. Now I've seen you've already committed that change. Great!
