### ISSUE TITLE
Possible version clash in Flask-JWT dependencies

### ISSUE THREAD

**Issue by mablanco** [j3ssie/Osmedeus#65]
Hi j3ssie,

Installing Osmedeus under Debian 10, I've found that Flask-JWT install PyJWT 1.4.2:
```
Collecting PyJWT<1.5.0,>=1.4.0 (from Flask-JWT==0.3.2->-r requirements.txt (line 4))
```
while Flask-JWT-Extended asks for PyJWT>=1.6.4:
```
flask-jwt-extended 3.18.1 has requirement PyJWT>=1.6.4, but you'll have pyjwt 1.4.2 which is incompatible
```
Maybe lowering Flask-JWT-Extended version could be a solution? Or is this just only happening in Debian 10?

Best regards.

**Comment by j3ssie** [comment]
Yeah, that's warning is fine.
You may consider switch to `FROM kalilinux/kali-linux-docker` for more more convenient because I often test it on Kali box :D.

**Comment by mablanco** [comment]
Yes, I was pondering that option. I want to make some tests with that image.

**Comment by mablanco** [comment]
Hi again. I've just tried using the `kalilinux/kali-linux-docker` image but the warning is still there:
```
flask-jwt-extended 3.18.1 has requirement PyJWT>=1.6.4, but you'll have pyjwt 1.4.2 which is incompatible.
```
I'll disregard it as you said if it isn't important. Best regards.

**Comment by j3ssie** [comment]
Hi @mablanco,
I've just upgrade **Osmedeus v2.0**. Can you take a look and build a docker file for it?
Best regards,
