### ISSUE TITLE
Gitrob / Gitleacks Install issue

### ISSUE THREAD

**Issue by Hax0rG1rl** [j3ssie/Osmedeus#67]
**Env:** Xubuntu 18.04, fully patched. 

**Install type:** sudo ./install.sh

Hi,

As an FYI, I get this issue while I am trying to install the latest standalone version. 

![image](https://user-images.githubusercontent.com/3704868/62886510-56751f00-bd8f-11e9-9e43-1c998c53715b.png)

![image](https://user-images.githubusercontent.com/3704868/62886538-6987ef00-bd8f-11e9-89ed-308d7a78e280.png)

Thanks.

**Comment by j3ssie** [comment]
Looks like you have problem with your network, just run a install again you'll be fine.
