### ISSUE TITLE
slack problem

### ISSUE THREAD

**Issue by degilq** [j3ssie/osmedeus#72]
I put my env on the ~/.bashrc, but when run Osmedeus, then rewrite /root/.osmedeus/config.conf  with bot_token = None and slack_bot_token not work yet

I put my env with:

 vi ~/.bashrc

export BOT_TOKEN=xoxb-2347015xxxxx
export SLACK_BOT_TOKEN=xoxb-2347015xxxxxxHa7ShEi
export LOG_CHANNEL=xxxx
export STATUS_CHANNEL=xxxx
export STDS_CHANNEL=xxxx
export REPORT_CHANNEL=xxxx
export VERBOSE_REPORT_CHANNEL=xxxxx

**Comment by j3ssie** [comment]
Make sure Osmedeus got your token and channel by view the slack section in `.osmedeus/config.conf`

You need to enable it via `--slack` options is Osmedeus.
Just run `./osmedeus.py -t  example.com --slack`

**Comment by dwisiswant0** [comment]
> Make sure Osmedeus got your token and channel by view the slack section in `.osmedeus/config.conf`
> 
> You need to enable it via `--slack` options is Osmedeus.
> Just run `./osmedeus.py -t example.com --slack`

hi bro, there's no file at `.osmedeus/config.conf`, and when i try to reload by `python3 scripts/reload.py`, my `server.conf` revert to default.

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
