### ISSUE TITLE
Installation for LinkFinder fails

### ISSUE THREAD

**Issue by mablanco** [j3ssie/Osmedeus#73]
Hi j3ssie,

I've cloned the repo today and found that commit cf33e15 provokes this error when installing:

```
./install.sh: line 185: cd: LinkFinder/: No such file or directory
[+] Installing LinkFinder 
python2.7: can't open file 'setup.py': [Errno 2] No such file or directory
```
It happens because the `install.sh` script tries to change into a directory that doesn't exists yet:
```
cd LinkFinder/
install_banner "LinkFinder"
git clone https://github.com/GerbenJavado/LinkFinder.git 2> /dev/null
python2.7 setup.py install
```
Just `cd` after `git clone` and it'll be fixed. Best regards.

**Comment by j3ssie** [comment]
Hi @mablanco, I'll fix it soon.

I'm planning to upgrade **Osmedeus v2** based on Django with real Database and new awesome feature give it more elegant and more powerful.

In the meantime, you can stop build docker for the legacy code here and wait for me to push the new version(maybe next week).

**Comment by mablanco** [comment]
Hi, those are really good news! I was just trying to use kalilinux as base image instead of Debian 10 (no great differences in the end), that's how I got that error. I'll wait for you and see if I can dockerize v2 without problems (Django can be a beast when trying to run it inside a container).
