### ISSUE TITLE
Can't access the Web UI

### ISSUE THREAD

**Issue by Tarekzidan19** [j3ssie/Osmedeus#74]
I have two VPS 
Upuntu 16.06 from DigitalOcean
Kali linux from Amazon AWS

i installed the tool by cloninng the repo and then == ./install.sh
it worked great in both of them but i can't access the WEB UI
when i go to https://my-public-server-ip:5000 i got and error
This site can’t be reached

**Comment by j3ssie** [comment]
Well, you need to bind the server on `0.0.0.0` or do SSH tunnel to access via localhost.
run the command below on your local machine and access it via https://localhost:5000
```
ssh -L 5000:localhost:5000 root@your_remote_server
```

By the way, I'm about to upgrade a completely new version of Osmedeus so this not gonna works on next release.
Will make a new docs for remote access don't worry
