### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by PikachuBunny** [j3ssie/Osmedeus#75]
Hey there,

I am a mega noob. But did everything you did in the installation on youtube.  Whenever I want to start the application, I get this error>
Traceback (most recent call last):
  File "./osmedeus.py", line 9, in <module>
    from lib.core import utils
  File "/root/Desktop/Osmedeus/lib/core/utils.py", line 24, in <module>
    import tldextract
ModuleNotFoundError: No module named 'tldextract'

Seems like I miss the tldextract module. I cannot seem to find it on github either. Could you please help me ? :)

**Comment by j3ssie** [comment]
Did you use **python 3.7**?
Check your version by using this command `python3 --version`

**Comment by Tarekzidan19** [comment]
run 
# pip3 install tldextract
it solver the problem for me

**Comment by j3ssie** [comment]
Nice, will test to add to requirements.txt. It's defaulted on my machine 😃

**Comment by rijinrij** [comment]
root@MrCyguru:/home/cyguru/Desktop/scan/Osmedeus# python osmedeus.py -h
Traceback (most recent call last):
  File "osmedeus.py", line 9, in <module>
    from lib.core import utils
ImportError: No module named core
root@MrCyguru:/home/cyguru/Desktop/scan/Osmedeus# pip3 install utils
Requirement already satisfied: utils in /usr/local/lib/python3.8/dist-packages (1.0.1)
root@MrCyguru:/home/cyguru/Desktop/scan/Osmedeus#
