### ISSUE TITLE
There is no core folder, and when I start, I can’t go to 127.0.0.1:5000

### ISSUE THREAD

**Issue by robdollard** [j3ssie/Osmedeus#77]
There is no core folder, and when I start, I can’t go to 127.0.0.1:5000. When switching to 127.0.0.1:8080, the following occurs.
![image](https://user-images.githubusercontent.com/40629638/64612166-93fbb500-d3ec-11e9-86b7-8c844b1a2e5d.png)
![image](https://user-images.githubusercontent.com/40629638/64612200-a70e8500-d3ec-11e9-90c8-a1e39d16b078.png)

**Comment by j3ssie** [comment]
Pull the latest commit and it should be fixed now.

This happened because I forget to fix UI path when running `python3 server/manage.py runserver` instead of run `python3 manage.py runserver` which I usually use when developing.
