### ISSUE TITLE
Waiting for Initials Module

### ISSUE THREAD

**Issue by gru3zi** [j3ssie/Osmedeus#8]
Seems to be stuck on waiting for initials module. 

![image](https://user-images.githubusercontent.com/44057919/55303695-385ef000-547a-11e9-8543-6b85260cf263.png)

**Comment by raulcpop** [comment]
[*] Waiting for Initials module
 Same :)

**Comment by v5pingan** [comment]
Like you...

 - [*] Waiting for Initials module

--------------------------
There's nothing in the report.

![Image 1.png](https://i.loli.net/2019/04/01/5ca1b2aa5cf77.png)

**Comment by j3ssie** [comment]
I just tested on clean Kali install and still don't see that issue.
Btw I also update times to wait for a module, if specified Osmedeus will force continue no matter something went wrong with a module.

P/s: if you would't mind, just DM me about the target via @j3ssiejjj for detail.

**Comment by j3ssie** [comment]
And btw the UI didn't show anything because the module was not done so nothing to show.
I'll close the issue for now. Please reopen if it still fails on machine.
