### ISSUE TITLE
Notify when detected new data

### ISSUE THREAD

**Issue by theblackturtle** [j3ssie/osmedeus#82]
Hi, I think It will be nice if it save the result by date like `~/.osmedeus/workspaces/09-13-2019/domain.com`. With this, we can run a new task without remove old data, and we can check which are the new informations.

**Comment by j3ssie** [comment]
I'm also planning this feature. My idea still keeps the same structure of output but adding DB table for notification when new port detected.

Will consider later when base features stable.
Thank you for the feedback.

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
