### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by sieunhando** [j3ssie/Osmedeus#83]
#### install.sh
- Install chromium (on Ubuntu)
`sudo apt-get install chromium-browser`
  - If use this chromium, the default path is `/usr/bin/chromium-browser` (need to be set if use **gowitness**)
- Install unzip (unzip is not installed as default)
`sudo apt-get install unzip`

#### Others
- webanalyze threads should be `cpu core * 2`

**Comment by j3ssie** [comment]
Thanks for mention will update to install file soon. Will make compatible for ubuntu soon when I have more time to test on fresh ubuntu machine :).
