### ISSUE TITLE
Check and use one chrome browser

### ISSUE THREAD

**Issue by sieunhando** [j3ssie/Osmedeus#84]
Hi, I think we should check chrome browser path before running `aquatone` and `gowitness` because `gowitness` is not updated for a long time so it missing some chrome path such as `/usr/bin/chromium-browser`(aquatone have it).

Also, the chromium package in ubuntu is `chromium-browser` not `chromium`, you can check it at https://packages.ubuntu.com/search?keywords=chromium

**Comment by sieunhando** [comment]
One more thing, I think It will be nice if you focus in Ubuntu/Debian because it popular than Kali Linux and easy to build in server. Not many cloud services support custom ISO installer. Ubuntu/Debian is also weight light than Kali Linux so it will take less resource.

**Comment by j3ssie** [comment]
Thanks for mention will update to install file soon.
Yeah, I use Kali (install will work well on Debian) because their default package repo look more better. Will make compatible for ubuntu soon when I have more time to test on fresh ubuntu machine :).
