### ISSUE TITLE
Can't change credentials in Osmedeus V2

### ISSUE THREAD

**Issue by Intek13x** [j3ssie/Osmedeus#87]
Osmedeus does not start after changing credentials in client.conf file. Is there some other config files which i have to change in order to make it work? 

Here is the trimmed output - 

sudo ./osmedeus.py -t github.com

                                       `@@`
                                      @@@@@@
                                    .@@`  `@@.
                                    :@      @:
                                    :@  :@  @:                       
                                    :@  :@  @:                       
                                    :@      @:                             
                                    `@@.  .@@`
                                      @@@@@@
                                        @@
                                     @  @@  @               
                                    +@@ @@ @@+                    
                                 @@:@#@,@@,@#@:@@           
                                ;@+@@`#@@@@#`@@+@;
                                @+ #@@@@@@@@@@# +@
                               @@  @+`@@@@@@`+@  @@
                               @.  @   ;@@;   @  .@
                              #@  '@          @;  @#

                           Osmedeus v2.0 by @j3ssiejjj

                                    ¯\_(ツ)_/¯
        
[*] Loading config file from: /root/.osmedeus/client.conf
----------------------------------------------------------------------
----------------------------------------------------------------------
[RUN] Starting Django API
----------------------------------------------------------------------
Performing system checks...

System check identified no issues (0 silenced).
September 18, 2019 - 06:19:16
Django version 2.2.5, using settings 'rest.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
----------------------------------------------------------------------
Unauthorized: /auth/api/token/
[18/Sep/2019 06:19:18] "POST /auth/api/token/ HTTP/1.1" 401 63
[-] Authentication failed
[-] Can't login to get JWT

**Comment by j3ssie** [comment]
You can create new user from by following this [guide](https://j3ssie.github.io/Osmedeus/installation/user-management/).

For the error, did you get credentials from `~/.osmedeus/client.conf` file?
If you don't create new use or change the old one by running this [script](https://github.com/j3ssie/Osmedeus/blob/master/scripts/init.py).

Just delete `~/.osmedeus/` folder and run `python3 scripts/init.py` again.
Let me know if you have any issue.

**Comment by Intek13x** [comment]
I got it working perfectly. Thanks for the help. I should've read documentation properly.
