### ISSUE TITLE
Skip module in real time

### ISSUE THREAD

**Issue by linkbc** [j3ssie/osmedeus#88]
I'd like to be allowed to skip a module on-the-fly, could be useful when a module is stuck (e.g. dirb)
By the way, great job!

**Comment by henryharan** [comment]
my scan also stuck on Starting DirbScan section, any way to skip that?

**Comment by j3ssie** [comment]
Thank you for the feedback!
I think maybe I will switch back to dirsearch with simple wordlist and add an option to exclude module.

**Comment by attacker34** [comment]
Hi @j3ssie  there is an option of  -x 'linkfinding,dirb' in readme file but its not working.. It should skip dirb scan module but its saying 

````
osmedeus.py: error: unrecognized arguments: -x linkfinding,dirb                                                                              

````

**Comment by AhmedOzil10** [comment]
Hello I have the same error , I have written -x 'dirb' and it doesn't skip dirb scan mode it just keep telling me that this module is ignored and stop

**Comment by hansnewton** [comment]
Hello @henryharan try like this:
-x "linkfinding"

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
