### ISSUE TITLE
/bin/sh: 1: None/bin... not found

### ISSUE THREAD

**Issue by rdek** [j3ssie/Osmedeus#9]
```
/bin/sh: 1: None/bin/subfinder: not found
Something went wrong with the command below:
None/bin/subfinder -d site.com -t 100 -o /opt/Osmedeus/workspaces/site.com/subdomain/site.com-subfinder.txt -nW
```
```
/bin/sh: 1: None/bin/gobuster: not found
Something went wrong with the command below:
None/bin/gobuster -m dns -np -t 100 -w /opt/Osmedeus/plugins/wordlists/shorts.txt -u site.com -o /opt/Osmedeus/workspaces/site.com/subdomain/raw-site.com-gobuster.txt
```
```
/bin/sh: 1: None/bin/amass: not found
Something went wrong with the command below:
None/bin/amass -active -d site.com -o /opt/Osmedeus/workspaces/site.com/subdomain/sitecom-amass.txt
```

**Comment by purplesec** [comment]
I have the same error, im in kali.

**Comment by j3ssie** [comment]
That's happened because your current shell didn't sourcing `~/.bashrc`.
Simply open a new terminal or run command `source ~/.bashrc`.

P/s: I'm also fixed that on install script so just clean the folder and clone the repo again.

**Comment by purplesec** [comment]
> That's happened because your current shell didn't sourcing `~/.bashrc`.
> Simply open a new terminal or run command `source ~/.bashrc`.
> 
> P/s: I'm also fixed that on install script so just clean the folder and clone the repo again.

Delete repo and clone again, same error. What did it for me was sourcing bash rc file, now I will try this interesting tool.
