### ISSUE TITLE
Installation for amass fails

### ISSUE THREAD

**Issue by sugarp0pe** [j3ssie/Osmedeus#99]
Hello, j3ssie
I have some issues with amass during docker build 
<details>
  <summary>Errors log</summary>
  [+] Installing Update Golang version 
[+] Installing amass 
# github.com/OWASP/Amass/graph
/root/go/src/github.com/OWASP/Amass/graph/graph.go:93:26: not enough arguments in call to p.BuildIterator
	have ()
	want (context.Context)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:93:37: not enough arguments in call to p.BuildIterator().Optimize
	have ()
	want (context.Context)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:94:10: it.Close undefined (type iterator.Shape has no field or method Close)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:98:8: it.Next undefined (type iterator.Shape has no field or method Next)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:99:14: it.Result undefined (type iterator.Shape has no field or method Result)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:451:26: not enough arguments in call to p.BuildIterator
	have ()
	want (context.Context)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:451:37: not enough arguments in call to p.BuildIterator().Optimize
	have ()
	want (context.Context)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:452:10: it.Close undefined (type iterator.Shape has no field or method Close)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:456:8: it.Next undefined (type iterator.Shape has no field or method Next)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:457:14: it.Result undefined (type iterator.Shape has no field or method Result)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:457:14: too many errors
[+] Installing subfinder 
[+] Installing gobuster 
</details>

**Comment by j3ssie** [comment]
What's your go version?
Can you install amass directly via this command `go get -u github.com/OWASP/Amass/...`?

**Comment by sugarp0pe** [comment]
It is output from 
docker build -t osmedeus from Dockerfile from master branch repo
<details>
[+] Installing Update Golang version 
[+] Installing amass 
# github.com/OWASP/Amass/graph
/root/go/src/github.com/OWASP/Amass/graph/graph.go:93:26: not enough arguments in call to p.BuildIterator
	have ()
	want (context.Context)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:93:37: not enough arguments in call to p.BuildIterator().Optimize
	have ()
	want (context.Context)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:94:10: it.Close undefined (type iterator.Shape has no field or method Close)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:98:8: it.Next undefined (type iterator.Shape has no field or method Next)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:99:14: it.Result undefined (type iterator.Shape has no field or method Result)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:451:26: not enough arguments in call to p.BuildIterator
	have ()
	want (context.Context)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:451:37: not enough arguments in call to p.BuildIterator().Optimize
	have ()
	want (context.Context)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:452:10: it.Close undefined (type iterator.Shape has no field or method Close)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:456:8: it.Next undefined (type iterator.Shape has no field or method Next)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:457:14: it.Result undefined (type iterator.Shape has no field or method Result)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:457:14: too many errors
[+] Installing subfinder 
[+] Installing gobuster 
[+] Installing aquatone
[+] Installing gitrob 
[+] Installing subjack 
[+] Installing tko-subs 
[+] Installing subzy 
[+] Installing goaltdns 
[+] Installing gitleaks 
[+] Installing gowitness 
[+] Installing webanalyze 
[+] Installing assetfinder 
[+] Installing waybackurls 
[+] Installing meg 
[+] Installing httprobe 
[+] Installing unfurl 
[+] Installing filter-resolved 
[+] Installing ffuf 
[+] Installing rgf 
[+] Installing go cli-utils 
[+] Installing massdns 
Cloning into 'massdns'...
mkdir -p bin
cc  -O3 -std=c11 -DHAVE_EPOLL -DHAVE_SYSINFO -Wall -fstack-protector-strong main.c -o bin/massdns
[+] Installing findomain 
[+] Installing truffleHog, wfuzz 
Collecting truffleHog
  Downloading https://files.pythonhosted.org/packages/a3/6d/a251a89aae727260c32491a52ff01fcb2002141f455e9e9fd9c794824b5c/truffleHog-2.0.99-py2.py3-none-any.whl
Collecting truffleHogRegexes==0.0.7 (from truffleHog)
  Downloading https://files.pythonhosted.org/packages/7d/e3/5f800360d7f0b68f935fcd06ec18ec28802b931aa4bf6caef20de00b6546/truffleHogRegexes-0.0.7-py2.py3-none-any.whl
Collecting GitPython==2.1.1 (from truffleHog)
  Downloading https://files.pythonhosted.org/packages/0b/4b/b50901e779e9b651f2f60cdcdfc62620d73cc0140eef441052d7ab1b540f/GitPython-2.1.1-py2.py3-none-any.whl (441kB)
Collecting gitdb2>=2.0.0 (from GitPython==2.1.1->truffleHog)
  Downloading https://files.pythonhosted.org/packages/03/6c/99296f89bad2ef85626e1df9f677acbee8885bb043ad82ad3ed4746d2325/gitdb2-2.0.6-py2.py3-none-any.whl (63kB)
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->GitPython==2.1.1->truffleHog)
  Downloading https://files.pythonhosted.org/packages/55/d2/866d45e3a121ee15a1dc013824d58072fd5c7799c9c34d01378eb262ca8f/smmap2-2.0.5-py2.py3-none-any.whl
Installing collected packages: truffleHogRegexes, smmap2, gitdb2, GitPython, truffleHog
Successfully installed GitPython-2.1.1 gitdb2-2.0.6 smmap2-2.0.5 truffleHog-2.0.99 truffleHogRegexes-0.0.7
[+] Installing rgf signatures 
[+] Installing Metabigor 
Requirement already satisfied: requests==2.22.0 in /usr/local/lib/python3.7/dist-packages (from -r Metabigor/requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: lxml==4.3.4 in /usr/local/lib/python3.7/dist-packages (from -r Metabigor/requirements.txt (line 2)) (4.3.4)
Collecting beautifulsoup4==4.6.3 (from -r Metabigor/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/21/0a/47fdf541c97fd9b6a610cb5fd518175308a7cc60569962e776ac52420387/beautifulsoup4-4.6.3-py3-none-any.whl (90kB)
Collecting PyGithub==1.43.8 (from -r Metabigor/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/13/66/5c510242526d162708ffc0c82fd5ba647886f07d7abcae8587adeec86411/PyGithub-1.43.8.tar.gz (108kB)
Requirement already satisfied: tldextract==2.2.0 in /usr/local/lib/python3.7/dist-packages (from -r Metabigor/requirements.txt (line 5)) (2.2.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests==2.22.0->-r Metabigor/requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests==2.22.0->-r Metabigor/requirements.txt (line 1)) (2019.9.11)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests==2.22.0->-r Metabigor/requirements.txt (line 1)) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests==2.22.0->-r Metabigor/requirements.txt (line 1)) (1.25.6)
Collecting deprecated (from PyGithub==1.43.8->-r Metabigor/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/88/0e/9d5a1a8cd7130c49334cce7b8167ceda63d6a329c8ea65b626116bc9e9e6/Deprecated-1.2.6-py2.py3-none-any.whl
Requirement already satisfied: pyjwt in /usr/local/lib/python3.7/dist-packages (from PyGithub==1.43.8->-r Metabigor/requirements.txt (line 4)) (1.7.1)
Requirement already satisfied: requests-file>=1.4 in /usr/local/lib/python3.7/dist-packages (from tldextract==2.2.0->-r Metabigor/requirements.txt (line 5)) (1.4.3)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from tldextract==2.2.0->-r Metabigor/requirements.txt (line 5)) (40.8.0)
Collecting wrapt<2,>=1.10 (from deprecated->PyGithub==1.43.8->-r Metabigor/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/23/84/323c2415280bc4fc880ac5050dddfb3c8062c2552b34c2e512eb4aa68f79/wrapt-1.11.2.tar.gz
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from requests-file>=1.4->tldextract==2.2.0->-r Metabigor/requirements.txt (line 5)) (1.12.0)
Building wheels for collected packages: PyGithub, wrapt
  Running setup.py bdist_wheel for PyGithub: started
  Running setup.py bdist_wheel for PyGithub: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/ba/9a/c3/d8a3dd0f2574b8fd4c43fea45385773c3bcbb1cae80d05f9ed
  Running setup.py bdist_wheel for wrapt: started
  Running setup.py bdist_wheel for wrapt: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/d7/de/2e/efa132238792efb6459a96e85916ef8597fcb3d2ae51590dfd
Successfully built PyGithub wrapt
Installing collected packages: beautifulsoup4, wrapt, deprecated, PyGithub
  Found existing installation: beautifulsoup4 4.7.1
    Not uninstalling beautifulsoup4 at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'beautifulsoup4'. No files were found to uninstall.
Successfully installed PyGithub-1.43.8 beautifulsoup4-4.6.3 deprecated-1.2.6 wrapt-1.11.2
[+] Installing bass 
Collecting tldextract==2.2.1 (from -r bass/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/1e/90/18ac0e5340b6228c25cc8e79835c3811e7553b2b9ae87296dfeb62b7866d/tldextract-2.2.1-py2.py3-none-any.whl (48kB)
Collecting pyfiglet==0.8.post1 (from -r bass/requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/33/07/fcfdd7a2872f5b348953de35acce1544dab0c1e8368dca54279b1cde5c15/pyfiglet-0.8.post1-py2.py3-none-any.whl (865kB)
Collecting colorama==0.3.7 (from -r bass/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/b7/8e/ddb32ddaabd431813e180ca224e844bab8ad42fbb47ee07553f0ec44cd86/colorama-0.3.7-py2.py3-none-any.whl
Collecting dnspython==1.16.0 (from -r bass/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/ec/d3/3aa0e7213ef72b8585747aa0e271a9523e713813b9a20177ebe1e939deb0/dnspython-1.16.0-py2.py3-none-any.whl (188kB)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from tldextract==2.2.1->-r bass/requirements.txt (line 1)) (40.8.0)
Requirement already satisfied: requests>=2.1.0 in /usr/local/lib/python3.7/dist-packages (from tldextract==2.2.1->-r bass/requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: requests-file>=1.4 in /usr/local/lib/python3.7/dist-packages (from tldextract==2.2.1->-r bass/requirements.txt (line 1)) (1.4.3)
Requirement already satisfied: idna in /usr/local/lib/python3.7/dist-packages (from tldextract==2.2.1->-r bass/requirements.txt (line 1)) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests>=2.1.0->tldextract==2.2.1->-r bass/requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.1.0->tldextract==2.2.1->-r bass/requirements.txt (line 1)) (1.25.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.1.0->tldextract==2.2.1->-r bass/requirements.txt (line 1)) (2019.9.11)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from requests-file>=1.4->tldextract==2.2.1->-r bass/requirements.txt (line 1)) (1.12.0)
Installing collected packages: tldextract, pyfiglet, colorama, dnspython
  Found existing installation: tldextract 2.2.0
    Uninstalling tldextract-2.2.0:
      Successfully uninstalled tldextract-2.2.0
Successfully installed colorama-0.3.7 dnspython-1.16.0 pyfiglet-0.8.post1 tldextract-2.2.1
[+] Installing dirsearch 
[+] Installing Arjun 
[+] Installing CORStest 
[+] Installing LinkFinder 
Collecting jsbeautifier (from -r LinkFinder/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/aa/46/47ac2168543690cb836106d11f16c6cc6323dd928f7b37f42b177cb8f9ac/jsbeautifier-1.10.2.tar.gz (69kB)
Collecting editorconfig>=0.12.2 (from jsbeautifier->-r LinkFinder/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/2e/7a/aedb7e1cba1778c1d78c4f6ad88d4b0dfca6b991befa248164121091d911/EditorConfig-0.12.2.tar.gz
Requirement already satisfied: six>=1.12.0 in /usr/lib/python3/dist-packages (from jsbeautifier->-r LinkFinder/requirements.txt (line 1)) (1.12.0)
Building wheels for collected packages: jsbeautifier, editorconfig
  Running setup.py bdist_wheel for jsbeautifier: started
  Running setup.py bdist_wheel for jsbeautifier: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/f0/1b/08/477c53e9a925a26b0b0f38f3346af6491ada52a7f7ce07b9e8
  Running setup.py bdist_wheel for editorconfig: started
  Running setup.py bdist_wheel for editorconfig: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/59/74/2e/26b7344c51a5786512d40c70a3653892dc52bcb99880f22c24
Successfully built jsbeautifier editorconfig
Installing collected packages: editorconfig, jsbeautifier
Successfully installed editorconfig-0.12.2 jsbeautifier-1.10.2
running install
running bdist_egg
running egg_info
creating LinkFinder.egg-info
writing LinkFinder.egg-info/PKG-INFO
writing dependency_links to LinkFinder.egg-info/dependency_links.txt
writing requirements to LinkFinder.egg-info/requires.txt
writing top-level names to LinkFinder.egg-info/top_level.txt
writing manifest file 'LinkFinder.egg-info/SOURCES.txt'
reading manifest file 'LinkFinder.egg-info/SOURCES.txt'
writing manifest file 'LinkFinder.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying LinkFinder.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying LinkFinder.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying LinkFinder.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying LinkFinder.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying LinkFinder.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/LinkFinder-1.0-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing LinkFinder-1.0-py3.7.egg
Copying LinkFinder-1.0-py3.7.egg to /usr/local/lib/python3.7/dist-packages
Adding LinkFinder 1.0 to easy-install.pth file

Installed /usr/local/lib/python3.7/dist-packages/LinkFinder-1.0-py3.7.egg
Processing dependencies for LinkFinder==1.0
Searching for argparse
Reading https://pypi.org/simple/argparse/
Downloading https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl#sha256=c31647edb69fd3d465a847ea3157d37bed1f95f19760b11a47aa91c04b666314
Best match: argparse 1.4.0
Processing argparse-1.4.0-py2.py3-none-any.whl
Installing argparse-1.4.0-py2.py3-none-any.whl to /usr/local/lib/python3.7/dist-packages
Adding argparse 1.4.0 to easy-install.pth file

Installed /usr/local/lib/python3.7/dist-packages/argparse-1.4.0-py3.7.egg
Searching for jsbeautifier==1.10.2
Best match: jsbeautifier 1.10.2
Adding jsbeautifier 1.10.2 to easy-install.pth file
Installing js-beautify script to /usr/local/bin

Using /usr/local/lib/python3.7/dist-packages
Searching for six==1.12.0
Best match: six 1.12.0
Adding six 1.12.0 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for EditorConfig==0.12.2
Best match: EditorConfig 0.12.2
Adding EditorConfig 0.12.2 to easy-install.pth file
Installing editorconfig script to /usr/local/bin

Using /usr/local/lib/python3.7/dist-packages
Finished processing dependencies for LinkFinder==1.0
[+] Installing done... 
Removing intermediate container 9c83627061a5
 ---> 2c86366e9566
Step 9/9 : ENTRYPOINT ["python3", "server/manage.py", "runserver", "0.0.0.0:8000"]
 ---> Running in 221e07f31d50
Removing intermediate container 221e07f31d50
 ---> 93b8deb39d7b
Successfully built 93b8deb39d7b
Successfully tagged osmedeus:latest
</details>

**Comment by edoz90** [comment]
Same error using docker

```
[+] Installing amass 
# github.com/OWASP/Amass/graph
/root/go/src/github.com/OWASP/Amass/graph/graph.go:93:26: not enough arguments in call to p.BuildIterator
	have ()
	want (context.Context)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:93:37: not enough arguments in call to p.BuildIterator().Optimize
	have ()
	want (context.Context)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:94:10: it.Close undefined (type iterator.Shape has no field or method Close)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:98:8: it.Next undefined (type iterator.Shape has no field or method Next)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:99:14: it.Result undefined (type iterator.Shape has no field or method Result)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:451:26: not enough arguments in call to p.BuildIterator
	have ()
	want (context.Context)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:451:37: not enough arguments in call to p.BuildIterator().Optimize
	have ()
	want (context.Context)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:452:10: it.Close undefined (type iterator.Shape has no field or method Close)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:456:8: it.Next undefined (type iterator.Shape has no field or method Next)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:457:14: it.Result undefined (type iterator.Shape has no field or method Result)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:457:14: too many errors
```

Installing `amass` on the container with the default command:

```
root@edaa8493e2e6:/home/Osmedeus# go get -u github.com/OWASP/Amass/...
# github.com/OWASP/Amass/config
/root/go/src/github.com/OWASP/Amass/config/support.go:54:19: undefined: os.UserConfigDir
```
https://github.com/OWASP/Amass/issues/260

Let me know if you need anything else

**Comment by j3ssie** [comment]
What go version in that docker?
Can you try to install docker from this update https://github.com/mablanco/docker-osmedeus?

**Comment by edoz90** [comment]
> What go version in that docker?

I used your docker-compose config.

```
root@f83ea8d32c22:/home/Osmedeus# go version
go version go1.11.6 linux/amd64
```

>  Can you try to install docker from this update https://github.com/mablanco/docker-osmedeus?

Same error during the build and manually

```
root@2f6ad618a4a8:/home/Osmedeus# go version
go version go1.11.6 linux/amd64
root@2f6ad618a4a8:/home/Osmedeus# go get -u github.com/OWASP/Amass/...
# github.com/OWASP/Amass/config
/root/go/src/github.com/OWASP/Amass/config/support.go:54:19: undefined: os.UserConfigDir
```

**Comment by j3ssie** [comment]
Okay, let me ask him to update the dockerfile.
Meanwhile, try to update your go version manually then install it again

**Comment by edoz90** [comment]
This line:

`wget -qO- https://raw.githubusercontent.com/udhos/update-golang/master/update-golang.sh | bash 2>/dev/null`

Installs the new version in `/usr/local/go/bin/` but this path in not in `$PATH`: `/root/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

```
root@1ae9cb404736:/home/Osmedeus# /usr/local/go/bin/go version
go version go1.13.3 linux/amd64
```
Anyway installing `amass` with then new go version returns the same errors

```
root@1ae9cb404736:/home/Osmedeus# /usr/local/go/bin/go get -u github.com/OWASP/Amass/...
# github.com/OWASP/Amass/graph
/root/go/src/github.com/OWASP/Amass/graph/graph.go:93:26: not enough arguments in call to p.BuildIterator
	have ()
	want (context.Context)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:93:37: not enough arguments in call to p.BuildIterator().Optimize
	have ()
	want (context.Context)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:94:10: it.Close undefined (type iterator.Shape has no field or method Close)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:98:8: it.Next undefined (type iterator.Shape has no field or method Next)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:99:14: it.Result undefined (type iterator.Shape has no field or method Result)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:451:26: not enough arguments in call to p.BuildIterator
	have ()
	want (context.Context)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:451:37: not enough arguments in call to p.BuildIterator().Optimize
	have ()
	want (context.Context)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:452:10: it.Close undefined (type iterator.Shape has no field or method Close)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:456:8: it.Next undefined (type iterator.Shape has no field or method Next)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:457:14: it.Result undefined (type iterator.Shape has no field or method Result)
/root/go/src/github.com/OWASP/Amass/graph/graph.go:457:14: too many errors
```

In `install.sh` the `$GO_BIN` var is set from `$(which go)` that is `/usr/bin/go` (old version).

**Comment by j3ssie** [comment]
Yeah, I appreciate that. I will look for another good way to install it.

**Comment by edoz90** [comment]
Is there news?

**Comment by edoz90** [comment]
> https://github.com/OWASP/Amass/blob/master/doc/install.md

To install `amass`:

`GO111MODULE=on go get -v -u github.com/OWASP/Amass/v3/...`

**Comment by sugarp0pe** [comment]
@edoz90 
Hey, can you please share your dockerfile or docker-compose config? I'd really appreciate it.

**Comment by j3ssie** [comment]
I've just fix the install script with `GO111MODULE=on` and it works fine for me. Let me know if you have any issue

**Comment by edoz90** [comment]
Seems good to me, thank you.

I've also forced `$GO_BIN` to `/usr/local/go/bin/go` but we need a better way to deal with this.

I think that you can close this issue

**Comment by j3ssie** [comment]
Yeah, that's just a latest version of go, your `$GO_BIN` will become normal when the script is done or when you open new terminal tab.
